unoplatform/Uno.Themes

- src/library/Uno.Material/Styles/Application/Colors.xaml
- src/library/Uno.Material/Styles/Controls/Button.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/ButtonSamplePage.xaml
GitHub Issue: #1
- Feature
- Contained, Outlined, and text buttons styles
- Updated onsurfacemedium and onsurfacedisabled colors
- Updated color names for buttons
- Added various states for hover, focus and pressed
- Added todo for success/dragged button state with elevation
- If the pull request contains breaking changes, commit message must contain a detailed description of the action to take for the consumer of this library. As explained by the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)
> Feature: Button + todo: dragged/success button state

- src/library/Uno.Material/MaterialLibraryResources.cs
- src/library/Uno.Material/Styles/Application/Colors.xaml
- src/library/Uno.Material/Styles/Application/SelectionControlColors.xaml
- src/library/Uno.Material/Styles/Controls/Button.xaml
- src/library/Uno.Material/Styles/Controls/CheckBox.xaml
- src/library/Uno.Material/Uno.Material.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/CheckBoxSamplePage.xaml
- Feature
Applied right color resources
- If the pull request contains breaking changes, commit message must contain a detailed description of the action to take for the consumer of this library. As explained by the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)
> Feat: Checkbox colors

- .github/pull_request_template.md
GitHub Issue: #n/a
minor cosmetic fix for pr template
> style: pr template cosmetic fix

- src/library/Uno.Material/MaterialLibraryResources.cs
- src/library/Uno.Material/Styles/Application/Colors.xaml
- src/library/Uno.Material/Styles/Application/SelectionControlColors.xaml
- src/library/Uno.Material/Styles/Controls/ToggleSwitch.xaml
- src/library/Uno.Material/Uno.Material.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/ToggleSwitchSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/ToggleSwitchSamplePage.xaml.cs
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/SamplesPage.xaml.cs
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Uno.Material.Samples.Shared.projitems
GitHub Issue: #11
- Feature
- Native toggleswitch styles for uwp, wasm, ios, and android
- To Dos for some issues found
> Feature: ToggleSwitch

- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/SamplesPage.xaml
> chore: Remove SearchBox

- src/library/Uno.Material/Converters/FromEmptyStringToValueConverter.cs
- src/library/Uno.Material/Styles/Application/Colors.xaml
- src/library/Uno.Material/Styles/Controls/TextBox.xaml
- src/library/Uno.Material/Uno.Material.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/TextBoxSamplePage.xaml
GitHub Issue: #6 
Feature
Applied styling changes for the Material TextBox
> Refactor: Applied styling changes for the Material TextBox

- src/library/Uno.Material/Uno.Material.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Droid/Uno.Material.Samples.Droid.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.UWP/Uno.Material.Samples.UWP.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Wasm/Uno.Material.Samples.Wasm.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.iOS/Uno.Material.Samples.iOS.csproj
Updates to the feature branch styles-compat to get access to the required features for this library!
> Update to styles feature branch

- src/library/Uno.Material/Styles/Controls/TextBox.xaml
GitHub Issue: #6
Applied the animated focus for TextBox
> Style: Applied the animated focus for TextBox

- src/library/Uno.Material/Styles/Application/Colors.xaml
- src/library/Uno.Material/Styles/Controls/Button.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/FabSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/FabSamplePage.xaml.cs
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/SamplesPage.xaml.cs
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Uno.Material.Samples.Shared.projitems
- Feature
- Fab for icons and text+icons
- Known issue for wasm ElevatedView and Ellipse Fill with opacity
> Feature: FAB

- src/library/Uno.Material/Styles/Application/SelectionControlColors.xaml
- src/library/Uno.Material/Styles/Controls/ToggleSwitch.xaml
GitHub Issue: #11
- Bugfix
- fixes android off toggle color, and uwp unfocus
> fix(toggleswitch): android off toggle color, and uwp unfocus

- src/library/Uno.Material/Styles/Application/Colors.xaml
> fix(color): Fixed OnPrimaryBrush Color

- src/library/Uno.Material/Styles/Application/Colors.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Styles/ColorsSamplePage.xaml
- Feature
Added content for the color sample page
#7
> Feat: Color sample Page

- src/library/Uno.Material/MaterialLibraryResources.cs
- src/library/Uno.Material/Styles/Controls/ComboBox.xaml
- src/library/Uno.Material/Uno.Material.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/ComboBoxSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/ComboBoxSamplePage.xaml.cs
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/SamplesPage.xaml.cs
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Uno.Material.Samples.Shared.projitems
> feat: ComboBox

- src/library/Uno.Material/Styles/Controls/Button.xaml
- src/library/Uno.Material/Styles/Controls/CheckBox.xaml
- src/library/Uno.Material/Styles/Controls/TextBox.xaml
- src/library/Uno.Material/Styles/Controls/ToggleSwitch.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/ButtonSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/CheckBoxSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/FabSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/RadioButtonSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/TextBlockSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/TextBoxSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/ToggleSwitchSamplePage.xaml
> feat: Show xaml for controls

- src/library/Uno.Material/Styles/Controls/Button.xaml
GitHub Issue: #49 
- Bugfix
- Fix to the nullref for not_win visual setters
> fix(nullref): Fix to the nullref for not_win visual setters

- README.md
- src/library/Uno.Material/Controls/Ripple.cs
- src/library/Uno.Material/MaterialLibraryResources.cs
- src/library/Uno.Material/Styles/Controls/Button.xaml
- src/library/Uno.Material/Styles/Controls/Card.xaml
- src/library/Uno.Material/Styles/Controls/Ripple.xaml
GitHub Issue: #35
- Feature
- Ripple effect added to buttons
> feat: Ripple Effect

- src/samples/Uno.Material.Samples/Uno.Material.Samples.iOS/LaunchScreen.storyboard
- src/samples/Uno.Material.Samples/Uno.Material.Samples.iOS/Uno.Material.Samples.iOS.csproj
- Feature
Added a temporary launchscreen for ios to meet CI requirements
> Feat: iOS Launchscreen

- Uno.Material.sln
- azure-pipelines.yml
- build/stage-release-testflight.yml
GitHub Issue: #24 
Add testflight deployment
> ci: Add testflight deployment

- src/library/Uno.Material/Styles/Controls/CheckBox.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/CheckBoxSamplePage.xaml
- Feature
Added animation on the checkboxes
> Feat: CheckBox Animation

- src/library/Uno.Material/Styles/Controls/RadioButton.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/RadioButtonSamplePage.xaml
> Feat: Radio button animation

- src/library/Uno.Material/Styles/Controls/Ripple.xaml
GitHub Issue: #35 
- Bugfix
Fixed SystemException for ripple effect (Multiple animations in the same containing Storyboard cannot target the same property on a single element).
> Fixed SystemException for ripple effect

- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/ButtonSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/CardsSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/CheckBoxSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/ComboBoxSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/FabSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/NavigationViewSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/RadioButtonSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/SnackBarSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/TextBlockSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/TextBoxSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/ToggleSwitchSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Styles/ColorsSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/SamplesPage.xaml.cs
- Feature
Remove redundant texts in samples
> feat: Remove redundant texts in samples

- src/library/Uno.Material/Styles/Controls/Button.xaml
- Bugfix
Change TextButton to PrimaryHover instead of OnSurfaceHover
> fix: Change TextButton to PrimaryHover instead of OnSurfaceHover #75

- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/CardsSamplePage.xaml
fix: Corrected spelling mistake in Cards
- Bugfix: Corrected spelling mistake in Cards
Corrected spelling mistake in Cards
> fix: Corrected spelling mistake in Cards

- src/library/Uno.Material/Styles/Controls/Card.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/CardsSamplePage.xaml
- Bugfix
[Android][Cards] Samples are cut off on the right side #85
#85
> fix: [Android][Cards] Samples are cut off on the right side #85

- src/library/Uno.Material/Styles/Controls/Button.xaml
> feat: Cleaning up button resources

- src/library/Uno.Material/Styles/Controls/ToggleSwitch.xaml
GitHub Issue: #90
- Bugfix
Fix header clipping on ios.
> fix: [iOS][ToggleSwitch] ToggleSwitch Label text is cut off #90

- src/library/Uno.Material/Styles/Application/Colors.xaml
- src/library/Uno.Material/Styles/Controls/BottomNavigationBar.xaml
- src/library/Uno.Material/Styles/Controls/BottomNavigationBarItem.xaml
GitHub Issue: #5 
- Bugfix
Add Ripple control
Fixed the Theme not changing BottomBar colors
> fix: Add Ripple effect to bottom bar + fixed the Theme not changing BottomBar colors

- src/library/Uno.Material/Styles/Application/Colors.xaml
- src/library/Uno.Material/Styles/Controls/CheckBox.xaml
- src/library/Uno.Material/Styles/Controls/ComboBox.xaml
- src/library/Uno.Material/Styles/Controls/CommandBar.xaml
- src/library/Uno.Material/Styles/Controls/RadioButton.xaml
- src/library/Uno.Material/Styles/Controls/TextBox.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/CheckBoxSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/ComboBoxSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/RadioButtonSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/SnackBarSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/TextBlockSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/TextBoxSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/ToggleSwitchSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Styles/ColorsSamplePage.xaml
> improvement : Cleanup of old colors

- src/library/Uno.Material/Uno.Material.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Droid/Uno.Material.Samples.Droid.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/App.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.UWP/Uno.Material.Samples.UWP.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Wasm/Uno.Material.Samples.Wasm.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.iOS/Uno.Material.Samples.iOS.csproj
GitHub Issue:  
Fixes #50 
Fixes #41 
- Bugfix
Update uno to have access to fixes made to the main repo
> chore: Update Uno to feature branch rebased on uno 3.0

- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/TextBoxSamplePage.xaml
GitHub Issue: #119
- Bugfix
Applied a fix for the multi-line TextBox sample
> Applied a fix for the multi-line TextBox sample

- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/SamplesPage.xaml.cs
GitHub Issue: #n/a
clean up menu initialization and sample navigation
> refactor: samples navigation

- src/library/Uno.Material/Styles/Controls/Ripple.xaml
GitHub Issue: #118
- Bugfix
fix the Ripple effect for ios and android.
DoubleAnimationUsingKeyFrames is not implemented/supported on uno for ios and android.
> fix: ripple for ios and android

- src/samples/Uno.Material.Samples/Uno.Material.Samples.Droid/MainActivity.cs
GitHub Issue: #129 
- Bugfix
fixed page content being partially blocked by soft keyboard on android.
resolved: #129
> fixed(android): content hidden by soft keyboard

- README.md
- src/library/Uno.Material/Styles/Application/Colors.xaml
- src/library/Uno.Material/Styles/Application/SelectionControlColors.xaml
- src/library/Uno.Material/Styles/Controls/ToggleSwitch.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Droid/Resources/values-night/colors.xml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Droid/Resources/values/Styles.xml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Droid/Resources/values/colors.xml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Droid/Uno.Material.Samples.Droid.csproj
GitHub Issue: #11 #122 
- Bugfix
- Refactor
- Implements proper brushes
- Removes todos
> fix(colors): ToggleSwitch colors fixed/updated

- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/SamplesPage.xaml.cs
GitHub Issue: #133
- Bugfix
- Added back fab page
- Fix Nav page
- Ordered Bottombar page
> fix(navigation): Some sample pages were not set up properly, bug fix

- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/FabSamplePage.xaml
GitHub Issue: #114
- Bugfix
- Added proper colors to fab label and icon content
> fix(labelColor): Fab label color fix

- src/library/Uno.Material/Styles/Controls/NavigationView.xaml
GitHub Issue: #135
- Bugfix
- Button background to transparent fixes issue
> fix(navView): Button quickly stretches and background visible while splitview is opening

- src/library/Uno.Material/Styles/Controls/SnackBar.xaml
GitHub Issue: #106
- Bugfix
- Fix error h_error e_fail, due to null refs
> fix(snackbar): Fixed Error binding nullref

- src/library/Uno.Material/Styles/Controls/Button.xaml
GitHub Issue: #94
- Bugfix
- Fix to fab shadow
- ~~increased elevation of smaller button~~
- added margin to other to prevent ripple from blocking shadow
> fix(shadow): Android fix to fab shadows

- src/library/Uno.Material/Styles/Controls/TextBox.xaml
GitHub Issue: #89
- Bugfix
fixed textbox placeholder text stuck in ios
resolved: #89
> fix(textbox): placeholder stuck on ios

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/ISSUE_TEMPLATE/samples-request.md
- .github/ISSUE_TEMPLATE/support.md
- .github/pull_request_template.md
With MacOS coming, preparing the issue template accordingly
> chore: Add macOS to our issue templates + update gitter to discord

- src/library/Uno.Material/Styles/Controls/BottomNavigationBarItem.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/BottomNavigationBarSamplePage.xaml
﻿## PR Type
- Bugfix
Tabs without text had incorrect placements when used alongside Badges.
> Applied UI fixes related to the badge and labeless tabs

- README.md
﻿GitHub Issue: fixes #162 
Getting started didn't mention where to get the nuget.
> Update readme to add dev feed

- README.md
Double "is a"
- Bugfix
- Feature
> Fixing small typo

- src/library/Uno.Material/Styles/Controls/NavigationView.xaml
﻿Gallery Issue: #192065
- Bugfix
- Prevents visible delay of collpasing heades
> fix(navigationView): Fix to headers collapsing with a delay

- src/library/Uno.Material/Styles/Controls/ToggleSwitch.xaml
> fix(toggleSwitch): Wasm namespace isn't working in a library project

- src/library/Uno.Material/Controls/Ripple.cs
Gallery Issue: #192142 
- Bugfix
- Wasm workaround limited to wasm projects
> fix(ripple): Isolates wasm nested ripple workaround

- src/library/Uno.Material/Styles/Controls/CheckBox.xaml
﻿GitHub Issue: #379
- Bugfix
- Workarounds the ios delay
> fix(checkBox): Fixes iOS press ring animation delay

- src/library/Uno.Material/Styles/Controls/ComboBox.xaml
﻿Gallery Issue: #190657 
- Bugfix
- Rounding of combobox popup corners
> fix(comboBox): ComboBox placement consistency

- README.md
- src/library/Uno.Material/Controls/Divider.cs
- src/library/Uno.Material/MaterialResources.cs
- src/library/Uno.Material/Styles/Controls/Divider.xaml
- src/library/Uno.Material/Uno.Material.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/DividerSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/DividerSamplePage.xaml.cs
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/SamplesPage.xaml.cs
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Uno.Material.Samples.Shared.projitems
- Feature
I've implemented the material divider control. 
> feat: divider control

- src/library/Uno.Material/MaterialResources.cs
- src/library/Uno.Material/Styles/Controls/HyperlinkButton.xaml
- src/library/Uno.Material/Uno.Material.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/HyperlinkButtonSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/HyperlinkButtonSamplePage.xaml.cs
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/NavigationViewSamplePage.xaml.cs
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/SamplesPage.xaml.cs
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Uno.Material.Samples.Shared.projitems
﻿GitHub Issue: #393 
- Feature
Added Hyperlink ButtonMaterial Styles
> Hyperlink Button #393

- src/library/Uno.Material/Styles/Application/AnimationConstants.xaml
- src/library/Uno.Material/Styles/Application/Converters.xaml
- src/library/Uno.Material/Styles/Controls/BottomNavigationBarItem.xaml
- src/library/Uno.Material/Styles/Controls/Button.xaml
- src/library/Uno.Material/Styles/Controls/Card.xaml
- src/library/Uno.Material/Styles/Controls/CheckBox.xaml
- src/library/Uno.Material/Styles/Controls/ComboBox.xaml
- src/library/Uno.Material/Styles/Controls/Divider.xaml
- src/library/Uno.Material/Styles/Controls/ExpandingBottomSheet.xaml
- src/library/Uno.Material/Styles/Controls/FloatingActionButton.xaml
- src/library/Uno.Material/Styles/Controls/NavigationView.xaml
- src/library/Uno.Material/Styles/Controls/NavigationView_PaneToggleButton.xaml
- src/library/Uno.Material/Styles/Controls/PasswordBox.xaml
- src/library/Uno.Material/Styles/Controls/RadioButton.xaml
- src/library/Uno.Material/Styles/Controls/SnackBar.xaml
- src/library/Uno.Material/Styles/Controls/TextBox.xaml
- src/library/Uno.Material/Styles/Controls/ToggleButton.xaml
- Feature
Adding animations and constant resources.
Also renaming some converters
Material_EaseInOutFunction -> MaterialEaseInOutFunction
Material_TrueToVisible -> MaterialTrueToVisible
Material_TrueToCollapsed -> MaterialTrueToCollapsed
Material_EmptyToFalse -> MaterialEmptyToFalse
Material_EmptyToTrue -> MaterialEmptyToTrue
Material_NullToCollapsedConverter -> MaterialNullToCollapsedConverter
Material_NullToVisibleConverter -> MaterialNullToVisibleConverter
Material_EmptyOrNullToVisible -> MaterialEmptyOrNullToVisible
Material_EmptyOrNullToCollapsed -> MaterialEmptyOrNullToCollapsed
- Commits must be following the [Conventional Commits …
> feature: Standardize Animations #391

- README.md
- src/library/Uno.Material/Controls/StandardBottomSheet/StandardBottomSheet.EventSubscriptions.cs
- src/library/Uno.Material/Styles/Controls/FloatingActionButton.xaml
- src/library/Uno.Material/Styles/Controls/StandardBottomSheet.xaml
﻿GitHub Issue: #401 #386
- Bugfix
- add doc
- gesture fix
- converter name fix
> fix(standardBottomSheets): Small fixes for StandardBottomSheets

- src/library/Uno.Material/Styles/Controls/StandardBottomSheet.xaml
﻿GitHub Issue: #386
- Bugfix
- Removed a default background color
> fix: Allows CustomHeader backgrounds the possibility of being transparent

- src/library/Uno.Material/Controls/ModalStandardBottomSheet.cs
﻿GitHub Issue: #401
- Bugfix
- quick fix to close sheet
> fix: FullScreen ModalStandardBottomSheet not closing properly

- README.md
- Sheet.md
- Uno.Material.sln
> docs: Added sheets md file

- src/library/Uno.Material/MaterialResources.cs
- src/library/Uno.Material/Styles/Controls/Flyout.xaml
- src/library/Uno.Material/Uno.Material.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/FlyoutSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/FlyoutSamplePage.xaml.cs
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/SamplesPage.xaml.cs
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Uno.Material.Samples.Shared.projitems
- Feature
Add Material styles for flyout components
> feat: Flyout Material Style

- README.md
> docs: Add code highlighting in readme

- src/library/Uno.Material/Styles/Controls/TimePicker.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/TimePickerSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/SamplesPage.xaml.cs
- Feature
Adding Material style for TimePicker
> feat: TimePicker Material Style

- src/library/Uno.Material/Converters/StringFormatConverter.cs
- src/library/Uno.Material/MaterialResources.cs
- src/library/Uno.Material/Styles/Application/Converters.xaml
- src/library/Uno.Material/Styles/Application/TextBoxVariables.xaml
- src/library/Uno.Material/Styles/Controls/DatePicker.xaml
- src/library/Uno.Material/Uno.Material.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/DatePickerSamplePage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/DatePickerSamplePage.xaml.cs
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/SamplesPage.xaml.cs
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Uno.Material.Samples.Shared.projitems
- Feature
Add Material Style for DatePicker
- ~~[ ] Tested WASM~~
> feat: Add Material Style for Date Picker

- src/library/Uno.Material/Uno.Material.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Droid/Uno.Material.Samples.Droid.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Skia.Gtk/Uno.Material.Samples.Skia.Gtk.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.UWP/Uno.Material.Samples.UWP.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Wasm/Uno.Material.Samples.Wasm.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.iOS/Uno.Material.Samples.iOS.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.macOS/Uno.Material.Samples.macOS.csproj
- Feature
Update to Uno 3.1.10 stable because it was currently on a 3.0-dev one.
> feat: update uno to 3.1.10

- src/library/Uno.Material/Styles/Application/TextBoxVariables.xaml
﻿GitHub Issue: fixes https://github.com/unoplatform/uno/issues/4905
- Bugfix
The type of the `TextBox` rounded corner resource as incorrect.
> fix(TextBox): Rounded corners resource type is incorrect

- src/library/Uno.Material/Controls/Ripple.cs
﻿GitHub Issue: fix unoplatform/uno#5033
- Bugfix
Nested `Ripple` controls no longer all animate when pressed. Instead only the innermost Ripple play its animation.
Because of #373, the animation is trigged on all `PointerPressedEvent` including `handledEventsToo`.
> fix(Ripple): only innermost Ripple should animate

- src/library/Uno.Material/Uno.Material.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Droid/Properties/AndroidManifest.xml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Droid/Uno.Material.Samples.Droid.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Helpers/SystemThemeHelper.cs
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/SamplesPage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/SamplesPage.xaml.cs
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Uno.Material.Samples.Shared.projitems
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Skia.Gtk/Uno.Material.Samples.Skia.Gtk.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.UWP/Uno.Material.Samples.UWP.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Wasm/Uno.Material.Samples.Wasm.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.iOS/Uno.Material.Samples.iOS.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.macOS/Uno.Material.Samples.macOS.csproj
- Feature
Adds a Light/Dark theme toggle to the samples
> feat: Add Light/Dark Toggle to samples

- src/library/Uno.Material/Styles/Controls/CheckBox.xaml
- src/library/Uno.Material/Styles/Controls/ToggleButton.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Droid/Uno.Material.Samples.Droid.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Skia.Gtk/Uno.Material.Samples.Skia.Gtk.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.UWP/Uno.Material.Samples.UWP.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Wasm/Uno.Material.Samples.Wasm.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.iOS/Uno.Material.Samples.iOS.csproj
- src/samples/Uno.Material.Samples/Uno.Material.Samples.macOS/Uno.Material.Samples.macOS.csproj
﻿GitHub Issue: fixes https://github.com/unoplatform/uno/issues/5053
> fix(reg): Disable animations for pressed states on CheckBox/ToggleButton

- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/App.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/SamplesPage.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/SamplesPage.xaml.cs
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Styles/ToggleButton.xaml
- src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Uno.Material.Samples.Shared.projitems
- Feature
Use ToggleButton for the theme switcher to match what's in Gallery
> feat: Use ToggleButton for theme switching

- .github/ISSUE_TEMPLATE/enhancement.md
> chore: Update enhancement.md

- src/library/Uno.Cupertino/CupertinoResources.cs
- src/library/Uno.Cupertino/Styles/Application/AnimationConstants.xaml
- src/library/Uno.Cupertino/Styles/Application/ColorPalette.xaml
- src/library/Uno.Cupertino/Styles/Application/Colors.xaml
- src/library/Uno.Cupertino/Styles/Controls/Button.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ButtonSamplePage.xaml
﻿GitHub Issue: #460
- Feature
Added new Cupertino button styles : default, contained and outlined.
> Add Cupertino Button

- azure-pipelines.yml
- Build or CI related changes:
> chore: Add xamarin.mac ci workaround

- src/library/Uno.Cupertino/Styles/Controls/ToggleSwitch.xaml
- src/library/Uno.Cupertino/Uno.Cupertino.csproj
- src/library/Uno.Material/Uno.Material.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Droid/Uno.Themes.Samples.Droid.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/App.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ToggleSwitchSamplePage.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Styles/ToggleSwitch.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Uno.Themes.Samples.Shared.projitems
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Skia.Gtk/Uno.Themes.Samples.Skia.Gtk.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.UWP/Uno.Themes.Samples.UWP.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Wasm/Uno.Themes.Samples.Wasm.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.iOS/Uno.Themes.Samples.iOS.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.macOS/Uno.Themes.Samples.macOS.csproj
- Bugfix
Update Uno packages
Add wasm: prefix workaround for ToggleSwitch styles
> chore: Update packages, add ToggleSwitch Workaround

- src/library/Uno.Cupertino/Styles/Controls/ProgressBar.xaml
- src/library/Uno.Cupertino/Styles/Controls/TextBox.xaml
﻿GitHub Issues: 
#465
#463
- Bugfix
Fix TextBox placeholder color name
Fix ProgressBar background color
> fix: Fix color style name

- src/library/Uno.Cupertino/Styles/Controls/Slider.xaml
﻿GitHub Issue: #505
- Feature
Change slider disabled state - change opacity of tick bar instead of gray colors.
> fix: Cupertino - Change slider disabled state

- src/library/Uno.Material/Styles/Controls/ProgressRing.xaml
- src/library/Uno.Material/Uno.Material.csproj
related https://github.com/unoplatform/uno/issues/5375
- Bugfix
Fixes issue with Material Progress Ring not showing up on WASM/iOS
> fix(ProgressRing): Use EmbeddedResource for Uno projects

- src/library/Uno.Cupertino/CupertinoResources.cs
- src/library/Uno.Cupertino/Styles/Controls/HyperlinkButton.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/HyperlinkButtonSamplePage.xaml
﻿GitHub Issue: #507
- Feature
Added Cupertino Hyperlink Button
> Add Hyperlink Button

- src/library/Uno.Material/Styles/Controls/ProgressRing.xaml
> fix: Fix path for ProgressRing asset on UWP

- src/library/Uno.Material/Uno.Material.csproj
﻿GitHub Issue: https://github.com/unoplatform/uno/issues/5375
- Bugfix
> fix(ProgressRing): Do not copy content to output for progress ring assets on UWP

- src/library/Uno.Material/MaterialResources.cs
- src/library/Uno.Material/Styles/Controls/Button.xaml
- src/library/Uno.Material/Styles/Controls/InfoBar.xaml
- src/library/Uno.Material/Styles/Controls/Ripple.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/InfoBarSamplePage.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/InfoBarSamplePage.xaml.cs
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Uno.Themes.Samples.Shared.projitems
> feat: Add Material InfoBar style

- src/library/Uno.Cupertino/Styles/Controls/Button.xaml
- src/library/Uno.Cupertino/Styles/Controls/TextBox.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/App.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/App.xaml.Navigation.cs
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ButtonSamplePage.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/TextBoxSamplePage.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/OverviewPage.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/OverviewPage.xaml.cs
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/OverviewPageHeader.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/OverviewPageHeader.xaml.cs
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Controls/OverviewSampleView.cs
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Styles/OverviewSampleView.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Uno.Themes.Samples.Shared.projitems
> Add initial Overview page

- src/library/Uno.Cupertino/CupertinoResources.cs
- src/library/Uno.Cupertino/Styles/Controls/ComboBox.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ComboBoxSamplePage.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ComboBoxSamplePage.xaml.cs
﻿GitHub Issue: #467 
- Feature
> combo box style and sample

- src/library/Uno.Cupertino/Styles/Controls/RadioButton.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/RadioButtonSamplePage.xaml
﻿GitHub Issue: #531 
#530 
- Bugfix
> Fix RadioButton style

- src/library/Uno.Cupertino/Styles/Controls/ComboBox.xaml
- Bugfix
Match what it should look like on iOS when adding a UIPickerView to a default UITextView
Before:
After:
> fix: ComboBox styling issues

- azure-pipelines.yml
- src/library/Uno.Cupertino/Styles/Controls/Button.xaml
- src/library/Uno.Cupertino/Styles/Controls/CheckBox.xaml
- src/library/Uno.Cupertino/Styles/Controls/ComboBox.xaml
- src/library/Uno.Cupertino/Styles/Controls/HyperlinkButton.xaml
- src/library/Uno.Cupertino/Styles/Controls/PasswordBox.xaml
- src/library/Uno.Cupertino/Styles/Controls/RadioButton.xaml
- src/library/Uno.Cupertino/Styles/Controls/Slider.xaml
- src/library/Uno.Cupertino/Styles/Controls/TextBlock.xaml
- src/library/Uno.Cupertino/Styles/Controls/TextBox.xaml
- src/library/Uno.Cupertino/Styles/Controls/ToggleSwitch.xaml
- src/library/Uno.Material/Styles/Controls/TextBlock.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/App.xaml.cs
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/ColorPaletteOverride.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/PasswordBoxSamplePage.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/SliderSamplePage.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/TextBlockSamplePage.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ToggleSwitchSamplePage.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Styles/ColorsSamplePage.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Styles/SamplePageLayout.xaml
> refactor: Clean up styles

- src/library/Uno.Cupertino/Styles/Controls/CheckBox.xaml
- src/library/Uno.Cupertino/Styles/Controls/RadioButton.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/App.xaml.Navigation.cs
﻿## PR Type
- Bugfix
Before:
After:
> fix: Wrap Whole Words for CheckBox/RadioButton, add Overview page as default

- src/library/Uno.Cupertino/CupertinoResources.cs
- src/library/Uno.Cupertino/Styles/Controls/NumberBox.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/NumberBoxSamplePage.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/NumberBoxSamplePage.xaml.cs
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/SamplesPage.xaml.cs
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Uno.Themes.Samples.Shared.projitems
﻿GitHub Issue: #522
- Feature
Add Cupertino styled NumberBox
> Add Cupertino NumberBox

- src/library/Uno.Material/Styles/Controls/Ripple.xaml
- Bugfix
Match Ripple animation durations constants compared to [Flutter](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/ink_ripple.dart)
> fix(Ripple): Update Ripple animation times

- src/library/Uno.Cupertino/Styles/Controls/CheckBox.xaml
- src/library/Uno.Cupertino/Styles/Controls/RadioButton.xaml
closes ﻿https://github.com/unoplatform/uno/issues/5552
- Bugfix
Before:
After:
> fix: [RadioButton/CheckBox] Add FocusRing

- src/library/Uno.Cupertino/Styles/Controls/ToggleSwitch.xaml
closes https://github.com/unoplatform/uno/issues/5636
- Bugfix
> fix(ToggleSwitch): Remove buggy shadow effect

- src/library/Uno.Material/Styles/Controls/Ripple.xaml
﻿GitHub Issue: related to https://github.com/unoplatform/uno/issues/5809
- Bugfix
`Ripple` should not be a tab stop
> fix: Ripple should not be a tab stop

- src/library/Uno.Cupertino/Uno.Cupertino.csproj
- src/library/Uno.Material/Uno.Material.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Droid/Uno.Themes.Samples.Droid.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Skia.Gtk/Uno.Themes.Samples.Skia.Gtk.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.UWP/Uno.Themes.Samples.UWP.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Wasm/Uno.Themes.Samples.Wasm.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.iOS/Uno.Themes.Samples.iOS.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.macOS/Uno.Themes.Samples.macOS.csproj
> chore: Update Uno packages

- src/library/Uno.Cupertino/Styles/Controls/DatePicker.xaml
- src/library/Uno.Material/Styles/Controls/DatePicker.xaml
https://github.com/unoplatform/uno/issues/5510
- Bugfix
> fix(DatePicker): Use nullable SelectedDate as DatePicker binding

- src/library/Uno.Cupertino/Uno.Cupertino.csproj
- src/library/Uno.Material/Uno.Material.csproj
> chore(deps): Update dependencies

- src/library/Uno.Cupertino/Uno.Cupertino.csproj
- src/library/Uno.Material/Styles/Controls/Ripple.xaml
- src/library/Uno.Material/Uno.Material.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Droid/Uno.Themes.Samples.Droid.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Skia.Gtk/Uno.Themes.Samples.Skia.Gtk.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.UWP/Uno.Themes.Samples.UWP.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Wasm/Uno.Themes.Samples.Wasm.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.iOS/Uno.Themes.Samples.iOS.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.macOS/Uno.Themes.Samples.macOS.csproj
closes https://github.com/unoplatform/uno/issues/6037
- Bugfix
> fix(Ripple): Add ContentTemplateSelector to Ripple

- src/library/Uno.Cupertino/Styles/Controls/ToggleSwitch.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Styles/ToggleSwitch.xaml
https://github.com/unoplatform/uno/issues/5941
- Bugfix
Before:
After:
> fix(ToggleSwitch): [Cupertino] Adjust CornerRadius/Fill

- src/library/Uno.Cupertino/CupertinoResources.cs
- src/library/Uno.Cupertino/Styles/Controls/CalendarDatePicker.xaml
- src/library/Uno.Cupertino/Styles/Controls/CalendarView.xaml
- src/library/Uno.Cupertino/Uno.Cupertino.csproj
- src/library/Uno.Material/Converters/FirstCharacterConverter.cs
- src/library/Uno.Material/MaterialResources.cs
- src/library/Uno.Material/Styles/Application/Converters.xaml
- src/library/Uno.Material/Styles/Controls/CalendarDatePicker.xaml
- src/library/Uno.Material/Styles/Controls/CalendarView.xaml
- src/library/Uno.Material/Uno.Material.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Droid/Uno.Themes.Samples.Droid.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/CalendarViewSamplePage.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/CalendarViewSamplePage.xaml.cs
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Uno.Themes.Samples.Shared.projitems
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Skia.Gtk/Uno.Themes.Samples.Skia.Gtk.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.UWP/Uno.Themes.Samples.UWP.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Wasm/Uno.Themes.Samples.Wasm.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.iOS/Uno.Themes.Samples.iOS.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.macOS/Uno.Themes.Samples.macOS.csproj
> feat(CalendarView): Add Material/Cupertino styles for CalendarView

- src/library/Uno.Cupertino/Styles/Controls/CalendarDatePicker.xaml
- src/library/Uno.Cupertino/Styles/Controls/CalendarView.xaml
- src/library/Uno.Material/Styles/Controls/CalendarDatePicker.xaml
- src/library/Uno.Material/Styles/Controls/CalendarView.xaml
- Bugfix
Fix crash on UWP due to missing colors reference + ControlCornerRadius reference
> fix(CalendarView): Fix crash on UWP

- src/library/Uno.Cupertino/Styles/Controls/CalendarView.xaml
- src/library/Uno.Material/Styles/Controls/CalendarView.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/App.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Styles/CalendarView.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Uno.Themes.Samples.Shared.projitems
- Bugfix
Add WASM specific style for CalendarView that includes changes from https://github.com/unoplatform/uno/pull/6197/files#diff-ee560a69818d96caaf2c004a44feb11d9f69b053352fd9ce3c4df11ea546744b
> fix(CalendarView): Add WASM workaround style

- src/library/Uno.Material/Controls/Chips/ChipGroup.cs
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ChipSamplePage.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Entities/Data/TestCollections.cs
﻿GitHub Issue: #612 
- Bugfix
Fix [Chip][Material][ChipGroup] SelectedItem with SelectionMode Single and SelectedItems with SelectionMode Multiple.
> fix(Chip): [Material][ChipGroup] SelectedItem and SelectedItems don't work

- src/library/Uno.Cupertino/CupertinoColors.cs
- src/library/Uno.Cupertino/CupertinoFonts.cs
- src/library/Uno.Material/MaterialColors.cs
- src/library/Uno.Material/MaterialFonts.cs
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/App.xaml
> Use OverrideSource for override properties

- src/library/Uno.Material/Styles/Controls/Button.xaml
> MaterialOutlinedButton should have a transparent background

- src/library/Uno.Material/Styles/Controls/ComboBox.xaml
> fix: ComboBox BorderBrush

- src/library/Uno.Material/MaterialResources.cs
- src/library/Uno.Material/Styles/Controls/ListView.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ListViewSamplePage.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ListViewSamplePage.xaml.cs
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Uno.Themes.Samples.Shared.projitems
> feat: Add Material ListView style

- src/library/Uno.Material/Styles/Controls/ListView.xaml
> Add Material ListView styles for SelectionMode and IsItemClickEnabled

- src/library/Uno.Material/MaterialResources.cs
- src/library/Uno.Material/Styles/Controls/RatingControl.xaml
> Add Material RatingControl styles

- src/library/Uno.Cupertino/Uno.Cupertino.csproj
- src/library/Uno.Material/Uno.Material.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Droid/Uno.Themes.Samples.Droid.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Skia.Gtk/Uno.Themes.Samples.Skia.Gtk.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.UWP/Uno.Themes.Samples.UWP.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Wasm/Uno.Themes.Samples.Wasm.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.iOS/Uno.Themes.Samples.iOS.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.macOS/Uno.Themes.Samples.macOS.csproj
> Bump Uno versions

- src/library/Uno.Material/Styles/Controls/HyperlinkButton.xaml
- Bugfix
Fix FontFamily resource for HyperlinkButton
> fix: FontFamily resource for HyperlinkButton

- README.md
- src/library/Uno.Cupertino/CupertinoResources.cs
- src/library/Uno.Cupertino/Styles/Controls/CalendarView.xaml
- src/library/Uno.Cupertino/Styles/Controls/CheckBox.xaml
- src/library/Uno.Cupertino/Styles/Controls/RadioButton.xaml
- src/library/Uno.Cupertino/Styles/Controls/Slider.xaml
- src/library/Uno.Material/MaterialResources.cs
- src/library/Uno.Material/Styles/Controls/CheckBox.xaml
- src/library/Uno.Material/Styles/Controls/ComboBox.xaml
- src/library/Uno.Material/Styles/Controls/CommandBar.xaml
- src/library/Uno.Material/Styles/Controls/DatePicker.xaml
- src/library/Uno.Material/Styles/Controls/NavigationView/NavigationView_MUX.xaml
- src/library/Uno.Material/Styles/Controls/RadioButton.xaml
- src/library/Uno.Material/Styles/Controls/RatingControl.xaml
- src/library/Uno.Material/Styles/Controls/Slider.xaml
- src/library/Uno.Material/Styles/Controls/TimePicker.xaml
﻿GitHub Issue: resolved: unoplatform/private#257
- Feature
Implicit styles are available with the `WithImplicitStyles` flag.
> feat: implicit styles

- src/library/Uno.Cupertino/Converters/FromEmptyStringToValueConverter.cs
- src/library/Uno.Cupertino/Converters/FromNullToValueConverter.cs
- src/library/Uno.Cupertino/Converters/StringFormatConverter.cs
- src/library/Uno.Cupertino/Styles/Application/Converters.xaml
- src/library/Uno.Cupertino/Styles/Controls/ComboBox.xaml
- src/library/Uno.Cupertino/Styles/Controls/Slider.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/App.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Shell.xaml
BREAKING CHANGE: Everything is now under `Uno.Cupertino`
Move everything under the Uno.Cupertino namespace
> refactor!: Move everything under the Uno.Cupertino namespace

- src/library/Uno.Material/Styles/Controls/Button.xaml
- src/library/Uno.Material/Styles/Controls/ComboBox.xaml
- src/library/Uno.Material/Styles/Controls/FloatingActionButton.xaml
- src/library/Uno.Material/Styles/Controls/PasswordBox.xaml
- src/library/Uno.Material/Styles/Controls/TextBox.xaml
- src/library/Uno.Material/Styles/Controls/ToggleButton.xaml
Fix a crash when reading an uninitialized attached property
﻿GitHub Issue: https://github.com/microsoft/microsoft-ui-xaml/issues/6388
> fix: Workaround for WinUI 3

- src/library/Uno.Material/MaterialResources.cs
- Bugfix
fix merge issue from #687, that:
- removed native mobile styling of `ToggleSwitch; and
- removed `ListView`+ `ListViewItem` styling
> fix: MaterialResources merge issues

- src/library/Uno.Cupertino/Uno.Cupertino.csproj
- src/library/Uno.Material/Uno.Material.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Droid/Uno.Themes.Samples.Droid.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Skia.Gtk/Uno.Themes.Samples.Skia.Gtk.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.UWP/Uno.Themes.Samples.UWP.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Wasm/Uno.Themes.Samples.Wasm.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.iOS/Uno.Themes.Samples.iOS.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.macOS/Uno.Themes.Samples.macOS.csproj
- Package update
Update Uno packages to latest stable 4.0.9
> chore: Update Uno packages to latest stable 4.0.9

- README.md
﻿GitHub Issue: #https://github.com/unoplatform/uno.toolkit.ui/issues/161
Add migration documentation from Uno.Themes version 1.0 to 1.1
> docs: Add migration documentation from 1.0 to 1.1

- README.md
- src/library/Uno.Material/Styles/Controls/NavigationView/WUX/NavigationView.xaml
﻿GitHub Issue: #n/a
- Bugfix
Update the list of style names that is exposed from this library.
> docs: update list of style names

- src/library/Uno.Material/Styles/Controls/ToggleSwitch.Mobile.xaml
- src/library/Uno.Material/Styles/Controls/ToggleSwitch.xaml
﻿GitHub Issue: resolved: unoplatform/uno.extensions#198
- Bugfix
fix MaterialToggleSwitchStyle min-width
https://github.com/microsoft/microsoft-ui-xaml/issues/6157
resolved: https://github.com/unoplatform/nventive-private/issues/318
> fix: material toggleswitch min-width

- src/library/Uno.Cupertino/Generated/mergedpages.xaml
- src/library/Uno.Cupertino/Styles/Controls/_Resources.xaml
- src/library/Uno.Cupertino/Uno.Cupertino.csproj
- src/library/Uno.Material/Generated/mergedpages.xaml
﻿GitHub Issue: fixes https://github.com/unoplatform/Uno.Themes/issues/708
- Bugfix
Fix invalid resources dictionary inclusion after resources merge.
> fix(reg): fix invalid UWP cupertino inclusion

- src/library/Uno.Cupertino/Generated/mergedpages.xaml
- src/library/Uno.Cupertino/Uno.Cupertino.csproj
- src/library/Uno.Material/Generated/mergedpages.xaml
- src/library/Uno.Material/Uno.Material.csproj
- src/library/Uno.Material/xamlmerge.targets
Adjusts for missing platform specific styles incorrectly removed as duplicates.
> fix(reg): Update xaml merge to restore missing platform specific styles

- src/library/Uno.Material/Styles/Controls/NavigationView/NavigationView_MUX.xaml
fixes https://github.com/unoplatform/uno.toolkit.ui/issues/185
- Bugfix
> fix: Avoid using RevealBrush in NavView Material style

- src/library/Uno.Cupertino/Styles/Controls/ToggleSwitch.xaml
- src/library/Uno.Material/Styles/Controls/ToggleSwitch.Base.xaml
- src/library/Uno.Material/Styles/Controls/ToggleSwitch.Mobile.xaml
- src/library/Uno.Material/Styles/Controls/ToggleSwitch.xaml
- src/library/Uno.Material/xamlmerge.targets
- Refactoring (no functional changes, no API changes)
Update `uno.xamlmerge.task` package to the latest (v1.0.0)
> If the pull request contains breaking changes, the commit message must contain a detailed description of the action to take for the consumer of this library. As explained by the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/#summary)
> chore: Update uno.xamlmerge.task to version 1.0.0

- src/library/Uno.Cupertino/CupertinoResources.cs
- src/library/Uno.Material/MaterialResources.cs
﻿GitHub Issue: n/a
- Bugfix
fixed uwp crash with WithImplicitStyles
> fix: uwp crash with WithImplicitStyles

- src/library/Uno.Cupertino/Styles/Controls/Button.xaml
- src/library/Uno.Cupertino/Styles/Controls/CheckBox.xaml
- src/library/Uno.Cupertino/Styles/Controls/RadioButton.xaml
- src/library/Uno.Material/Styles/Controls/Button.xaml
- src/library/Uno.Material/Styles/Controls/CheckBox.xaml
- src/library/Uno.Material/Styles/Controls/FloatingActionButton.xaml
- src/library/Uno.Material/Styles/Controls/RadioButton.xaml
- src/library/Uno.Material/Styles/Controls/ToggleButton.xaml
- src/library/Uno.Material/Styles/Controls/ToggleSwitch.xaml
closes https://github.com/unoplatform/nventive-private/issues/364
closes https://github.com/unoplatform/nventive-private/issues/366
- Bugfix
> Remove PointerFocused VisualState Setters

- src/library/Uno.Cupertino/Uno.Cupertino.csproj
- src/library/Uno.Material/Uno.Material.csproj
> chore: Bump Microsoft.Windows.SDK.NET.Ref to 10.0.22000.24

- src/library/Uno.Cupertino/Uno.Cupertino.csproj
- src/library/Uno.Material/Uno.Material.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Droid/Uno.Themes.Samples.Droid.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Skia.Gtk/Uno.Themes.Samples.Skia.Gtk.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.UWP/Uno.Themes.Samples.UWP.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Wasm/Uno.Themes.Samples.Wasm.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.iOS/Uno.Themes.Samples.iOS.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.macOS/Uno.Themes.Samples.macOS.csproj
> chore: bump uno dependencies and semver

- src/library/Uno.Material/Styles/Application/v2/SharedColorPalette.xaml
- src/library/Uno.Material/Styles/Application/v2/SharedColors.xaml
> fix: Add missing color brushes

- src/library/Uno.Material/Styles/Controls/v2/CommandBar.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/CommandBarSamplePage.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/CommandBarSamplePage.xaml.cs
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/NestedSamples/M3MaterialCommandBarSample_NestedPage1.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/NestedSamples/M3MaterialCommandBarSample_NestedPage1.xaml.cs
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/NestedSamples/M3MaterialCommandBarSample_NestedPage2.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/NestedSamples/M3MaterialCommandBarSample_NestedPage2.xaml.cs
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Uno.Themes.Samples.Shared.projitems
- Feature
Creation of M3MaterialAppBarButton, as it will be needed in Toolkit.Material for the M3MaterialNavigationBar.
Port legacy native CommandBar to M3 resources
> Add M3 CommandBar/AppBarButton styles

- src/library/Uno.Material/Styles/Controls/v2/Flyout.xaml
- src/library/Uno.Material/Uno.Material.csproj
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/FlyoutSamplePage.xaml
- Feature
Make v2 Flyouts look like this: https://m3.material.io/components/menus/overview
> feat: Add Material Design 3 Flyout styles

- src/library/Uno.Material/Styles/Controls/v2/CalendarDatePicker.xaml
- src/library/Uno.Material/Styles/Controls/v2/CalendarView.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/CalendarViewSamplePage.xaml
> feat: Add M3 CalendarView/Picker styles, fix broken styles

- src/library/Uno.Material/Generated/mergedpages.v2.xaml
- src/library/Uno.Material/Styles/Application/v2/SharedColorPalette.xaml
- src/library/Uno.Material/Styles/Application/v2/SharedColors.xaml
- src/library/Uno.Material/Styles/Controls/v2/Button.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ButtonSamplePage.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/OverviewPage.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Styles/SamplePageLayout.xaml
﻿GitHub Issue: #719 
- Feature
Add M3 Common Buttons styles and samples
> feat: Add M3 Common Buttons styles and samples

- src/library/Uno.Material/Styles/Controls/v2/ListView.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ListViewSamplePage.xaml
> feat: Add M3 ListView styles

- src/library/Uno.Material/MaterialResourcesV2.cs
- src/library/Uno.Material/Styles/Controls/v2/CommandBar.xaml
- src/library/Uno.Material/Styles/Controls/v2/PasswordBox.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/NestedSamples/M3MaterialCommandBarSample_NestedPage1.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/NestedSamples/M3MaterialCommandBarSample_NestedPage2.xaml
> feat: add style key aliases

- src/library/Uno.Material/MaterialResourcesV2.cs
- src/library/Uno.Material/Styles/Controls/v2/CalendarDatePicker.xaml
> feat: add more M3 implicit/shared styles

- src/library/Uno.Material/Styles/Controls/v2/ToggleButton.xaml
> feat: Add M3 ToggleButton styles

- src/library/Uno.Cupertino/Styles/Controls/ComboBox.xaml
- src/library/Uno.Material/Styles/Application/Common/Converters.xaml
- src/library/Uno.Material/Styles/Application/v2/SharedColors.xaml
- src/library/Uno.Material/Styles/Controls/v1/NavigationView/WUX/NavigationView_PaneToggleButton.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Converters.xaml
﻿GitHub Issue: #n/a
- Bugfix
add all opacity variants for brushes
> chore: add all opacity variants for brushes

- src/library/Uno.Material/Styles/Controls/v1/Button.xaml
closes https://github.com/unoplatform/nventive-private/issues/389
- Bugfix
> fix: Add back TextButton Unfocused VisualState Setters and remove PointerFocused Setters

- src/library/Uno.Material/MaterialResourcesV2.cs
- src/library/Uno.Material/Styles/Application/v2/SharedColorPalette.xaml
- src/library/Uno.Material/Styles/Controls/v2/NavigationView.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/NavigationViewSamplePage_MUX.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Controls/SamplePageLayout.cs
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Styles/SamplePageLayout.xaml
> feat: add M3 NavigationView + update default palette

- README.md
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.UWP/Uno.Themes.Samples.UWP.csproj
docs: Corrections to MacOS and .NET branding
> docs: terminology corrections

- src/library/Uno.Material/Styles/Application/v2/SharedColorPalette.xaml
- src/library/Uno.Material/Styles/Application/v2/SharedColors.xaml
Adding M2 Primary/Secondary Variant colors for compatibility
> chore: Add legacy variant colors to M3

- src/library/Uno.Material/MaterialResourcesV2.cs
- src/library/Uno.Material/Styles/Controls/v2/DatePicker.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/DatePickerSamplePage.xaml
> feat: Add M3 DatePicker

- src/library/Uno.Cupertino/Generated/mergedpages.xaml
- src/library/Uno.Material/Generated/mergedpages.v1.xaml
- src/library/Uno.Material/Generated/mergedpages.v2.xaml
- src/library/Uno.Material/Styles/Controls/v2/Button.xaml
chore: Use proper double for M3MaterialButton MinHeight and MinWidth
> chore: Use proper double for M3MaterialButton MinHeight and MinWidth

- src/library/Uno.Material/Styles/Controls/v2/Ripple.xaml
> fix: Bring default Ripple style to v2

- src/library/Uno.Material/MaterialResourcesV2.cs
- src/library/Uno.Material/Styles/Controls/v2/ComboBox.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ComboBoxSamplePage.xaml
> feat: Add M3 ComboBox

- README.md
Add synced contributors list for README.md
> docs: Add synced contributors list for README.md

- src/library/Uno.Material/Extensions/ControlExtensions.cs
- src/library/Uno.Material/Generated/mergedpages.v2.xaml
- src/library/Uno.Material/MaterialResourcesV2.cs
- src/library/Uno.Material/Styles/Controls/v2/FloatingActionButton.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/FabSamplePage.xaml
> feat: Add Material 3 FAB Styles

- src/library/Uno.Material/Styles/Controls/v2/CalendarDatePicker.xaml
closes https://github.com/unoplatform/Uno.Figma/issues/578
> fix: Use proper brush for CalendarDatePickerStyle Background

- azure-pipelines.yml
Change so the CI is not triggered if only docs files are changed
> ci: Change so the CI is not triggered if only docs files are changed

- src/library/Uno.Material/MaterialResourcesV2.cs
- src/library/Uno.Material/Styles/Controls/v2/Slider.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/SliderSamplePage.xaml
> feat: Add Material 3 Slider

- doc/material-controls-styles.md
- src/library/Uno.Material/Generated/mergedpages.v2.xaml
- src/library/Uno.Material/MaterialResourcesV2.cs
- src/library/Uno.Material/Styles/Controls/v2/HyperlinkButton.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/HyperlinkButtonSamplePage.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.UWP/Uno.Themes.Samples.UWP.csproj
﻿GitHub Issue: #719
- Feature
Add Material Design 3 HyperlinkButton styles
> feat: Material Design 3 HyperlinkButton

- doc/material-getting-started.md
- src/library/Uno.Material/Styles/Application/v2/SharedColorPalette.xaml
- Bugfix
Update SharedColorPalette for v2 with the latest colors
**Light Theme**
SecondaryContainerColor #E5DFF9
OnSecondaryContainerColor #1B192C
OnSurfaceVariantColor #A5A0AC
**Dark Theme**
SecondaryContainerColor #474459
OnSecondaryContainerColor #E5DFF9
**Figma M3 is already updated**
> fix: Update SharedColorPalette for v2 with latest colors

- src/library/Uno.Material/Generated/mergedpages.v2.xaml
- src/library/Uno.Material/Styles/Controls/v2/CheckBox.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/CheckBoxSamplePage.xaml
﻿GitHub Issue: https://github.com/unoplatform/Uno.Figma/issues/610
- Bugfix
Fix CheckBox label typo to match Uno Figma file
> fix: CheckBox label typo to match Uno Figma file

- src/library/Uno.Material/Styles/Controls/v2/TextBlock.xaml
Changed `FontWeight` of _Body_ typography on Material to follow guidelines.
> fix(font_weights): Fixed FontWeight for "Body" Material typos

- doc/material-controls-styles.md
- src/library/Uno.Material/MaterialResourcesV2.cs
- src/library/Uno.Material/Styles/Controls/v2/FloatingActionButton.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/FabSamplePage.xaml
> fix: FAB sizing issue

- src/library/Uno.Material/Generated/mergedpages.v2.xaml
- src/library/Uno.Material/Styles/Controls/v2/TextBlock.xaml
﻿GitHub Issue: https://github.com/unoplatform/Uno.Figma/issues/613
- Bugfix
Fix multiple typo issues for TextBlock to match Figma and Material M3 guidelines
More details here: https://github.com/unoplatform/Uno.Figma/issues/613#issuecomment-1145302377
> fix: Multiple typo issues for TextBlock to match Figma and Material M3 guidelines

- src/library/Uno.Material/Styles/Application/v2/SharedColorPalette.xaml
- src/library/Uno.Material/Styles/Controls/v2/ProgressBar.xaml
Fix wrong color in the palette + UI changes for ProgressBar
> fix: adjust color palette and progress bar

- src/library/Uno.Material/Generated/mergedpages.v2.xaml
- src/library/Uno.Material/Styles/Controls/v2/RadioButton.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/RadioButtonSamplePage.xaml
﻿GitHub Issue: https://github.com/unoplatform/Uno.Figma/issues/686
- Bugfix
Fixing gaps for the Material M3 RadioButton with the Uno Figma file guidelines
> fix: Fixing gaps for the Material M3 RadioButton with the Uno Figma file guidelines

- src/library/Uno.Material/Generated/mergedpages.v2.xaml
- src/library/Uno.Material/Styles/Controls/v2/ComboBox.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ComboBoxSamplePage.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Styles/SamplePageLayout.xaml
﻿GitHub Issue: fixes https://github.com/unoplatform/Uno.Figma/issues/674
- Bugfix
Fixing some gaps for the Material M3 ComboBox to match the Uno Figma file guidelines
> fix: Fixing some gaps for the Material M3 ComboBox to match the Uno Figma file guidelines

- src/library/Uno.Material/Generated/mergedpages.v2.xaml
- src/library/Uno.Material/Styles/Controls/v2/ToggleSwitch.xaml
﻿GitHub Issue: Fixes https://github.com/unoplatform/Uno.Figma/issues/685
- Bugfix
Fixing gaps for the Material M3 ToggleSwitch with the Uno Figma file guidelines
> fix: Fixing gaps for the Material M3 ToggleSwitch with the Uno Figma file guidelines

- src/library/Uno.Material/Styles/Controls/v2/ListView.xaml
closes https://github.com/unoplatform/uno/issues/8982
Remove unnecessary Setters on the default MaterialListViewStyle 
ListView style cleanup, remove unused styles
> fix: Adjust default Material ListView style

- src/library/Uno.Material/Generated/mergedpages.v1.xaml
- src/library/Uno.Material/Generated/mergedpages.v2.xaml
- src/library/Uno.Material/Styles/Application/Common/TextBoxVariables.xaml
- src/library/Uno.Material/Styles/Controls/v1/PasswordBox.xaml
- src/library/Uno.Material/Styles/Controls/v1/TextBox.xaml
- src/library/Uno.Material/Styles/Controls/v2/ComboBox.xaml
- src/library/Uno.Material/Styles/Controls/v2/PasswordBox.xaml
- src/library/Uno.Material/Styles/Controls/v2/TextBlock.xaml
- src/library/Uno.Material/Styles/Controls/v2/TextBox.xaml
﻿GitHub Issue: Resolves https://github.com/unoplatform/Uno.Figma/issues/678, Resolves https://github.com/unoplatform/uno/issues/8997
(﻿Other related issue: https://github.com/unoplatform/Uno.Figma/issues/713)
- Bugfix
Fix multiple gaps for M3 TextBox and PasswordBox to match Uno Figma file
> fix: Multiple gaps for M3 TextBox and PasswordBox to match Uno Figma file

- doc/material-migration.md
https://github.com/unoplatform/uno/discussions/9187
> docs: Address style key changes in migration

- src/library/Uno.Material/Generated/mergedpages.v2.xaml
- src/library/Uno.Material/Styles/Application/v2/Typography.xaml
- src/library/Uno.Material/Styles/Controls/v2/TextBlock.xaml
﻿GitHub Issue: closes #832
- Bugfix
fix text alignment
A value of 0 indicates that the line height is determined automatically from the current font characteristics.
> fix: text alignment

- src/library/Uno.Material/Styles/Controls/v2/PasswordBox.xaml
- src/library/Uno.Material/Styles/Controls/v2/TextBox.xaml
> fix: prevent text resize on pointerover

- src/library/Uno.Material/Generated/mergedpages.v2.xaml
- src/library/Uno.Material/Styles/Controls/v2/TextBox.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/TextBoxSamplePage.xaml
> fix(Textbox): Fix content and icon alignment for M3 Textboxes

- src/library/Uno.Material/Styles/Controls/v2/Button.xaml
because of missing template binding.
- Bugfix
- Feature
> fix(iconbutton): Setting a CornerRadius on IconButton were not working

- doc/material-migration.md
When updating from v1 to v2 I was having some issues with certain packages. Discovered that certain some packages had been moved around (in my case ControlExtensions.Icon and Ripple) but couldn't find any documentation about it, so i added it here. If this is documented somewhere let me know and i can close this PR …
> Docs: Updated migration document to include packages that have been moved

- src/library/Uno.Material/Styles/Controls/v2/ContentDialog.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ContentDialogSamplePage.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ContentDialogSamplePage.xaml.cs
﻿GitHub Issue: closes #637
- Bugfix
[corrected m3 ContentDialog style](fix: corrected m3 ContentDialog style)
> fix: corrected m3 ContentDialog style

- doc/material-migration.md
> docs: Fix NOTE content

- src/library/Uno.Material/Helpers/DictionaryHelper.cs
- src/library/Uno.Material/MaterialResourcesV2.cs
closes https://github.com/unoplatform/Uno.Themes/issues/865
> perf: Use lazy implicit styles for uno targets

- src/library/Uno.Material.WinUI.Markup/MarkupInit.cs
- src/library/Uno.Material.WinUI.Markup/Uno.Material.WinUI.Markup.csproj
- src/library/Uno.Material/MaterialColorsV2.cs
- src/library/Uno.Material/MaterialFonts.cs
- src/library/Uno.Themes.WinUI.Markup/Uno.Themes.WinUI.Markup.csproj
> feat: Add Material Markup init extensions

- Uno.Themes.sln
- src/library/Uno.Cupertino/Uno.Cupertino.csproj
- src/library/Uno.Material.WinUI.Markup/Uno.Material.WinUI.Markup.csproj
- src/library/Uno.Material/Uno.Material.csproj
- src/library/Uno.Themes.WinUI.Markup/Uno.Themes.WinUI.Markup.csproj
- winappsdk-workaround.targets
following what Jerome did here for Toolkit: https://github.com/unoplatform/uno.toolkit.ui/pull/147
> fix: add xbf workaround

- src/library/Uno.Material/Styles/Controls/v2/ToggleSwitch.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ToggleSwitchSamplePage.xaml
﻿GitHub Issue: 893
- Bugfix
Right now setting Foreground or Background of the ToggleSwitch should be reflected in the switch.
with this changes setting Background and Foreground be reflected in the switch.
1. Setting foreground: using this xaml the result is: `<ToggleSwitch Header="On change …
> fix: ToggleSwitch knob does not respect the Foreground property

- src/library/Uno.Material/Styles/Controls/v2/PipsPager.Base.xaml
- src/library/Uno.Material/Styles/Controls/v2/PipsPager.UWP.xaml
- src/library/Uno.Material/Styles/Controls/v2/PipsPager.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/PipsPagerSamplePage.xaml
﻿GitHub Issue: #[I106](https://github.com/unoplatform/uno.chefs/issues/106)
- Feature
Properly style the Material version for muxc:PipsPager to match Figma guidelines
> feat: Properly style the Material version for muxc:PipsPager to match Figma guidelines

- doc/cupertino-getting-started.md
- doc/material-getting-started.md
Add installation method for new solution template
> docs: update getting starteds

- src/library/Uno.Material/Styles/Application/v2/SharedColorPalette.xaml
closes https://github.com/unoplatform/Uno.Themes/issues/932
closes https://github.com/unoplatform/Uno.Themes/issues/934
closes https://github.com/unoplatform/Uno.Themes/issues/946
- Bugfix
```xml
<Color x:Key="OnPrimaryContainerColor">#170065</Color>
<Color x:Key="SecondaryColor">#6b4ea2</Color>
<Color x:Key="SecondaryVariantDarkColor">#3B2574</Color>
<Color x:Key="SecondaryVariantLightColor">#9B7BD5</Color>
<Color x:Key="SecondaryContainerColor">#EBDDFF</Color>
<Color x:Key="OnSecondaryContainerColor">#1F182B</Color>
NEW----> <Color x:Key="OutlineVariantColor">#C9C5D0</Color>
```
```xml
<Color x:Key="PrimaryColor">#C7BFFF</Color>
<Color x:Key="PrimaryInverseColor">#2A009F</Color>
<Color x:Key="OnPrimaryColor">#2A009F</Color>
<Color …
```
> fix: material default color palette corrections

- src/library/Uno.Cupertino/Styles/Controls/ComboBox.xaml
﻿GitHub Issue: re #900
- Bugfix
fix ComboBox::ItemTemplate and ItemTemplateSelector not being applied for Cupertino style
> fix(ComboBox): cupertino combo ItemTemplate

- src/library/Uno.Material/Styles/Controls/v2/CheckBox.xaml
- src/library/Uno.Material/Styles/Controls/v2/PasswordBox.xaml
- src/library/Uno.Material/Styles/Controls/v2/TextBox.xaml
related to https://github.com/unoplatform/uno.chefs/issues/396
> fix: checkbox and passwordbox colors

- doc/material-controls-styles.md
- src/library/Uno.Material/Styles/Controls/v2/_Resources.xaml
- src/library/Uno.Themes.WinUI.Markup/Theme.Styles.cs
- Bugfix
Add missing MenuFlyoutItemStyle implicit style and alias
> fix: Add missing MenuFlyoutItemStyle implicit style and alias

- src/library/Uno.Material/Extensions/ControlExtensions.cs
- src/library/Uno.Material/Extensions/SurfaceTintExtensions.cs
closes https://github.com/unoplatform/Uno.Themes/issues/960
> fix: Use fallback background tint

- Directory.Build.props
- Directory.Build.targets
- Directory.UnoMetadata.targets
- Feature
Package meta data in csproj
Meta data (including icon downloader) in targets file
> feat: Adding metadata targets file

- src/library/Uno.Material/Styles/Controls/v2/CheckBox.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/CheckBoxSamplePage.xaml
closes https://github.com/unoplatform/Uno.Themes/issues/987
Locally overridden with;
```xml
<SolidColorBrush x:Key="MaterialCheckBoxBackgroundUnchecked" Color="Red" />
<SolidColorBrush x:Key="MaterialCheckBoxBackgroundUncheckedPointerOver" Color="Red" />
<SolidColorBrush x:Key="MaterialCheckBoxBackgroundUncheckedPressed" Color="Red" />
<SolidColorBrush x:Key="MaterialCheckBoxBackgroundUncheckedDisabled" Color="Red" />
<SolidColorBrush x:Key="MaterialCheckBoxBackgroundChecked" Color="Blue" />
<SolidColorBrush x:Key="MaterialCheckBoxBackgroundCheckedPointerOver" Color="Blue" />
<SolidColorBrush x:Key="MaterialCheckBoxBackgroundCheckedPressed" Color="Blue" /> …
```
> refactor: Add lightweight styling resources for Material CheckBox

- src/library/Uno.Material/Styles/Controls/v2/ProgressRing.xaml
- src/library/Uno.Material/Styles/Controls/v2/ProgressRingWinUI.xaml
﻿GitHub Issue: #https://github.com/unoplatform/Uno.Themes/issues/993
Added Lightweight styling resources for ProgressRing control
||After modifying **ColorPaletteOverride.xaml** file|
|---|---|
|![Screenshot_1685474980](https://github.com/unoplatform/Uno.Themes/assets/34275909/a1f13500-0377-4c99-82c7-92028e3af681)|![Screenshot_1685501455](https://github.com/unoplatform/Uno.Themes/assets/34275909/95f5a84b-d0d9-4b3a-92f8-1c3c37b2af99)|
> refactor: add lightweight styling resources for ProgressRing control

- src/library/Uno.Material/Styles/Controls/v2/Button.xaml
﻿GitHub Issue: #https://github.com/unoplatform/Uno.Themes/issues/986
Added Lightweight styling resources for Button control
> refactor: add lightweight styling resources for Button control

- src/library/Uno.Material/Styles/Controls/v2/ComboBox.xaml
﻿GitHub Issue: #1005
Refactor ComboBox styles for Material to follow #894 
- ~~[ ] Tested MacOS~~
#1005
> refactor: Improve Lightweight styling for Material Combo Box

- src/library/Uno.Material/Styles/Controls/v2/DatePicker.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/DatePickerSamplePage.xaml
﻿GitHub Issue: #https://github.com/unoplatform/Uno.Themes/issues/1006
Added Lightweight styling resources for Datepicker control 
|||
|---|---|
|![Screenshot_1685645677](https://github.com/unoplatform/Uno.Themes/assets/34275909/ebc6ccf6-3d2e-47d2-af38-9047bbedd4b9)|![Screenshot_1685645664](https://github.com/unoplatform/Uno.Themes/assets/34275909/07fa392c-53b6-4b57-b0b7-50a33625b47e)|
|||
|---|---|
|![Screenshot_1685645852](https://github.com/unoplatform/Uno.Themes/assets/34275909/daaa767c-4172-4aec-b604-649563b0e14b)|![Screenshot_1685645839](https://github.com/unoplatform/Uno.Themes/assets/34275909/7e674da8-a547-4844-8b2f-de120af151c2)|
> refactor: add lightweight styling resources for Datepicker control

- src/library/Uno.Material/Styles/Controls/v2/FloatingActionButton.xaml
- src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/FabSamplePage.xaml
﻿GitHub Issue: #1007
Refactors resources for Material's FAB to follow lightweight styling conventions
#1007
> refactor: Add lightweight styling resources for Material Floating Action Button

- src/library/Uno.Material/Styles/Controls/v2/Button.xaml
- Bugfix
- Added missing Disabled button resource keys.
- Fixed a couple typos.
> fix: missing button styles

- src/library/Uno.Material/Styles/Controls/v2/CalendarDatePicker.xaml
closes #1036 #969
﻿GitHub Issue: #1036 #969
- Bugfix
Current behavior:
Overriden behavior:
Overriden with:
<Page.Resources>
<SolidColorBrush x:Key="CalendarDatePickerForeground"
Color="Red" />
<SolidColorBrush x:Key="CalendarDatePickerForegroundDisabled"
Color="Orange" />
<SolidColorBrush x:Key="CalendarDatePickerCalendarGlyphForeground"
Color="Yellow" />
<SolidColorBrush x:Key="CalendarDatePickerCalendarGlyphForegroundDisabled"
Color="Green" />
<SolidColorBrush x:Key="CalendarDatePickerTextForeground"
Color="Blue" />
<SolidColorBrush x:Key="CalendarDatePickerTextForegroundDisabled"
Color="Indigo" />
<SolidColorBrush x:Key="CalendarDatePickerTextForegroundSelected"
Color="Pink" /> …
> refactor(calendardatepicker): Add lightweight styling to CalendarDatePicker style

- src/library/Uno.Themes.WinUI.Markup/Theme.LightWeight/Themes.LightWeightStyles.Button.cs
﻿GitHub Issue: https://github.com/unoplatform/uno.csharpmarkup/issues/239
- Feature
> feat: Add lightweight styling to csharpmarkup button

- src/library/Uno.Material/Styles/Controls/v2/PasswordBox.xaml
- Bugfix
Fixed XAML parsing failed for MaterialOutlinedPasswordBoxStyle
> fix: XAML parsing failed for MaterialOutlinedPasswordBoxStyle

- src/library/Uno.Cupertino/Uno.Cupertino.csproj
- src/library/Uno.Material/Uno.Material.csproj
- src/samples/UWP/Uno.Themes.Samples.Skia.Gtk/Program.cs
- src/samples/UWP/Uno.Themes.Samples.Skia.Gtk/Uno.Themes.Samples.Skia.Gtk.csproj
- src/samples/UWP/Uno.Themes.Samples.UWP/Uno.Themes.Samples.UWP.csproj
- src/samples/UWP/Uno.Themes.Samples.Wasm/Uno.Themes.Samples.Wasm.csproj
- Bugfix
Unable to launch GTK sample due to GetWindow() exception
> fix: Fix GetWindow issue on GTK

- src/library/Uno.Themes.WinUI.Markup/Theme.Styles.cs
- src/library/Uno.Themes.WinUI.Markup/Theme/Button.cs
> refactor: change lightweight styling folder structure

- src/library/Uno.Material/Styles/Controls/v2/Slider.xaml
﻿GitHub Issue: #https://github.com/unoplatform/Uno.Themes/issues/992
- Feature
Added some resources to the themedictionnary and changed the look so that it is closer to figma 
Added resources to the lightweight styling 
https://github.com/unoplatform/Uno.Themes/issues/992
> feat(slider): adding other elements to lightweight styling

- Directory.Build.props
- src/library/Uno.Cupertino/Styles/Controls/ProgressRing.xaml
- src/library/Uno.Cupertino/Styles/Controls/ProgressRingWinUI.xaml
- src/library/Uno.Material/Styles/Controls/v1/ProgressRing.xaml
- src/library/Uno.Material/Styles/Controls/v1/ProgressRingWinUI.xaml
- src/library/Uno.Material/Styles/Controls/v1/ToggleSwitch.Mobile.xaml
- src/library/Uno.Material/Styles/Controls/v2/ProgressRing.xaml
- src/library/Uno.Material/Styles/Controls/v2/ProgressRingWinUI.xaml
- src/library/Uno.Material/Styles/Controls/v2/ToggleSwitch.xaml
> build: Disable XAML fuzzy matching

- src/library/Uno.Material/Styles/Controls/v2/Button.xaml
- src/library/Uno.Material/Styles/Controls/v2/CalendarDatePicker.xaml
- src/library/Uno.Material/Styles/Controls/v2/CalendarView.xaml
- src/library/Uno.Material/Styles/Controls/v2/CheckBox.xaml
- src/library/Uno.Material/Styles/Controls/v2/ComboBox.xaml
- src/library/Uno.Material/Styles/Controls/v2/CommandBar.xaml
- src/library/Uno.Material/Styles/Controls/v2/ContentDialog.xaml
- src/library/Uno.Material/Styles/Controls/v2/DatePicker.xaml
- src/library/Uno.Material/Styles/Controls/v2/Flyout.xaml
- src/library/Uno.Material/Styles/Controls/v2/HyperlinkButton.xaml
- src/library/Uno.Material/Styles/Controls/v2/ListView.xaml
- src/library/Uno.Material/Styles/Controls/v2/NavigationView.xaml
- src/library/Uno.Material/Styles/Controls/v2/PasswordBox.xaml
- src/library/Uno.Material/Styles/Controls/v2/PipsPager.UWP.xaml
- src/library/Uno.Material/Styles/Controls/v2/PipsPager.xaml
- src/library/Uno.Material/Styles/Controls/v2/ProgressBar.xaml
- src/library/Uno.Material/Styles/Controls/v2/ProgressRing.xaml
- src/library/Uno.Material/Styles/Controls/v2/ProgressRingWinUI.xaml
- src/library/Uno.Material/Styles/Controls/v2/RadioButton.xaml
- src/library/Uno.Material/Styles/Controls/v2/Ripple.xaml
- src/library/Uno.Material/Styles/Controls/v2/Slider.xaml
- src/library/Uno.Material/Styles/Controls/v2/TextBlock.xaml
- src/library/Uno.Material/Styles/Controls/v2/TextBox.xaml
- src/library/Uno.Material/Styles/Controls/v2/ToggleButton.xaml
- src/library/Uno.Material/Styles/Controls/v2/ToggleSwitch.xaml
- src/library/Uno.Material/Styles/Controls/v2/_Resources.xaml
﻿GitHub Issue: closes unoplatform/private#331
This PR refactors Uno.Themes v2 controls to make sure all of them include default explicit/implicit styles.
This file contains the code I used to test the styles and also in-app screenshots for the visual comparison for the three styles - the style that was used as default before the changes, the new default and the new default implicit:
[Styles test.docx](https://github.com/unoplatform/Uno.Themes/files/11959112/Styles.test.docx)
> If the pull request contains …
> refactor: check for missing explicit and implicit v2 styles

- src/library/Uno.Themes.WinUI.Markup/Theme.Styles.cs
- src/library/Uno.Themes.WinUI.Markup/Theme/ComboBox.cs
﻿GitHub Issue: # [[Lightweight Styling] ComboBox](https://github.com/unoplatform/uno.csharpmarkup/issues/247)
- Feature
add lightweight styling ComboBox
> feat: add lightweight styling to ComboBox

- src/library/Uno.Material/Styles/Controls/v2/PasswordBox.xaml
﻿GitHub PR: https://github.com/unoplatform/Uno.Themes/pull/1051
> refactor: Add resource in PasswordBox for the Glyph

- src/library/Uno.Themes.WinUI.Markup/Theme.Styles.cs
- src/library/Uno.Themes.WinUI.Markup/Theme/PasswordBox.cs
﻿GitHub Issue: https://github.com/unoplatform/uno.csharpmarkup/issues/242
- Feature
> feat(passwordbox): Add lightweight styling Password box

- src/library/Uno.Material/Styles/Controls/v2/HyperlinkButton.xaml
﻿GitHub Issue: n/a
Inline stray MaterialSecondaryHyperlinkButtonStyle resource
re: https://github.com/unoplatform/Uno.Themes/pull/1055#pullrequestreview-1526755910
> chore: adjust 2ndary hyperlink button resource

- src/library/Uno.Material/Styles/Controls/v2/Button.xaml
﻿GitHub Issue: #986 #1067
- Moving non-brush resources into ResourceDictionary.
> refactor(Button): lightweight styling for button

- src/library/Uno.Material/Styles/Controls/v2/TextBox.xaml
﻿GitHub Issue: https://github.com/unoplatform/Uno.Themes/issues/1067
non-brush lightweight styling for Textbox
> refactor: non-brush lightweight styling for Textbox

- src/library/Uno.Material/Styles/Controls/v2/NavigationView.xaml
> refactor(navigationview): Extract non-brush values into lightweight resources of NavigationView

- src/library/Uno.Material/Styles/Controls/v2/ToggleButton.xaml
﻿GitHub Issue: #1067
Create ResourceDictionary.
Move non-brush resources into ResourceDictionary.
> refactor(ToggleButton): lightweight styling for ToggleButton

- src/library/Uno.Material/Styles/Controls/v2/HyperlinkButton.xaml
﻿GitHub Issue: #1018 #1067
- Moving two resources to ResourceDictionary in HyperlinkButton XAML.
> refactor(HyperlinkButton): lightweight styling for hyperlinkbutton

- src/library/Uno.Material/Styles/Controls/v2/ToggleSwitch.xaml
﻿GitHub Issue: [Lightweight styling - ToggleSwitch](https://github.com/unoplatform/uno.csharpmarkup/issues/243)
add lightweight styling resources for ToggleSwitch control
> refactor: add lightweight styling resources for ToggleSwitch control

- src/library/Uno.Material/Styles/Controls/v2/FloatingActionButton.xaml
﻿GitHub Issue: #1067
Moving non-brush resources into ResourceDictionary.
> refactor(FAB): lightweight styling for button

- src/library/Uno.Material/Styles/Application/v2/SharedColorPalette.xaml
﻿GitHub Issue: https://github.com/unoplatform/Uno.Themes/issues/1143
fix default color palette based on figma
> style(palette): fix default color palette based on figma

- src/library/Uno.Cupertino/Uno.Cupertino.csproj
- src/library/Uno.Material/Styles/Controls/v2/PipsPager.Base.xaml
- src/library/Uno.Material/Uno.Material.csproj
- src/samples/UWP/Uno.Themes.Samples.Mobile/Uno.Themes.Samples.Mobile.csproj
- src/samples/UWP/Uno.Themes.Samples.Skia.Gtk/Uno.Themes.Samples.Skia.Gtk.csproj
- src/samples/UWP/Uno.Themes.Samples.UWP/Uno.Themes.Samples.UWP.csproj
- src/samples/UWP/Uno.Themes.Samples.Wasm/Uno.Themes.Samples.Wasm.csproj
#1063
#1009
- Feature
Added light weight styling for pipspager
> feat: added Pipspage lightweight styling

- src/library/Uno.Material/Styles/Application/v2/SharedColors.xaml
﻿GitHub Issue: https://github.com/unoplatform/Uno.Themes/issues/1150
- Bugfix
disabled text visibility
> fix: disabled text visibility

- .github/pull_request_template.md
- Other: PR Template
Update pull_request_template.md to add docs in PR Checklist
> chore: Update pull_request_template.md to add docs in PR Checklist

- src/library/Uno.Material/Styles/Application/v2/SharedColors.xaml
- src/library/Uno.Themes.WinUI.Markup/Theme.Brushes.cs
- src/samples/UWP/Uno.Themes.Samples.Shared/Content/Styles/ColorsSamplePage.xaml
﻿GitHub Issue: #1165
- Bugfix
Adding OutlineVariant brushes to SharedColors.xaml
> fix: Adding missing OutlineVariant brushes

- src/library/Uno.Themes.WinUI.Markup/Theme.Brushes.cs
﻿GitHub Issue: #1165
- Bugfix
Adding OutlineVariant brushes to Themes.Brushes.cs
> fix: Adding missing OutlineVariant brushes for markup

- doc/material-getting-started.md
Adding:
`<Color x:Key="OutlineVariantColor">#C9C5D0</Color>`
...
`<Color x:Key="OutlineVariantColor">#57545D</Color>`
> docs: Adding OutlineVariantColor to docs

- build/sign-package.ps1
> ci: Fail job on sign failure

- doc/material-migration.md
> docs: add migration for v3 resource keys

- src/library/Uno.Themes.WinUI.Markup/Theme.Styles.cs
- src/library/Uno.Themes.WinUI.Markup/Theme/CheckBox.cs
﻿GitHub Issue: https://github.com/unoplatform/uno.themes-private/issues/13
- Feature
> feat(checkbox): Add lightweight styling to Checkbox

- src/library/Uno.Themes.WinUI.Markup/Theme.Styles.cs
- src/library/Uno.Themes.WinUI.Markup/Theme/HyperlinkButton.cs
﻿GitHub Issue: closes https://github.com/unoplatform/uno.themes-private/issues/7
- Feature
- Continues lightweight styling for HyperlinkButton.
> feat(HyperlinkButton): lightweight styling for hyperlinkbutton

- src/library/Uno.Material/Styles/Controls/v2/ProgressBar.xaml
- src/library/Uno.Themes.WinUI.Markup/Theme.Styles.cs
- src/library/Uno.Themes.WinUI.Markup/Theme/ProgressBar.cs
- src/library/Uno.Themes.WinUI.Markup/Theme/ProgressRing.cs
﻿GitHub Issue: closes https://github.com/unoplatform/uno.themes-private/issues/6
- Feature
- Continues lightweight styling for ProgressBar and ProgressRing controls.
> feat(ProgressBar-ProgressRing): lightweight styling for ProgressBar-Ring

- src/library/Uno.Themes.WinUI.Markup/Themes/Slider.cs
﻿GitHub Issue: https://github.com/unoplatform/uno.themes-private/issues/9
- Feature
Lightweight styling setup for Material Slider
> feat(Slider): Lightweight styling for Material Slider

- src/library/Uno.Themes.WinUI.Markup/Themes/FloatingActionButton.cs
﻿GitHub Issue: [249](https://github.com/unoplatform/uno.themes-private/issues/10)
- Feature
Adds support for Material lightweight styling
> feat(FAB): Add Lightweight Styling to FloatingActionButton

- src/library/Uno.Themes.WinUI.Markup/Theme.Styles.cs
- src/library/Uno.Themes.WinUI.Markup/Theme/DatePicker.cs
﻿GitHub Issue: [Lightweight styling DatePicker](https://github.com/unoplatform/uno.themes-private/issues/8)
- Feature
add lightweight styling to DatePicker
> feat: add lightweight styling to DatePicker

- src/library/Uno.Themes.WinUI.Markup/Theme/ComboBox.cs
﻿GitHub Issue: https://github.com/unoplatform/uno.themes-private/issues/11
> refactor: refactoring lightweight styling resources on ComboBox

- src/library/Uno.Themes.WinUI.Markup/Theme.Styles.cs
- src/library/Uno.Themes.WinUI.Markup/Theme/TextBlock.cs
- src/library/Uno.Themes.WinUI.Markup/Theme/TextBox.cs
- src/library/Uno.Themes.WinUI.Markup/Theme/Typography.cs
﻿GitHub Issue: [Lightweight styling Typography](https://github.com/unoplatform/uno.themes-private/issues/4)
- Feature
add lightweight styling resources to Typography
> feat: add lightweight styling to Typography

- src/library/Uno.Material/Styles/Controls/v2/ListView.xaml
update ListViewItem style
update ListViewItem style
> chore: remove padding in ListViewItem

- crosstargeting_override.props.sample
﻿GitHub Issue: #1187 
- Bugfix
> Resolved WinUi issue for the crosstargeting file

- src/library/Uno.Cupertino/Styles/Controls/CheckBox.xaml
- src/library/Uno.Cupertino/Uno.Cupertino.csproj
- src/library/Uno.Material/Styles/Controls/v1/CheckBox.xaml
- src/library/Uno.Material/Styles/Controls/v2/CheckBox.xaml
- src/library/Uno.Material/Uno.Material.csproj
﻿GitHub Issue: Fixes #1197
- Bugfix
- Feature
> chore: Remove CheckBox workarounds from Skia/Wasm

- doc/material-controls-styles.md
- doc/styles/PasswordBox.md
- doc/styles/ToggleButton.md
PasswordBox default style is `OutlinedPasswordBoxStyle`.
ToggleButton default style is `IconToggleButtonStyle`.
> docs: Update Material Default Styles

- src/library/Uno.Material/Styles/Controls/v2/ListView.xaml
- Bugfix
- Feature
Add padding 0 to MaterialListViewItemStyle
> feat: Add padding 0 to MaterialListViewItemStyle

- src/library/Uno.Themes.WinUI.Markup/Theme/PipsPager.cs
closes https://github.com/unoplatform/uno.themes-private/issues/1
> feat: add lightweight styling markup resource for pipspager

- src/library/Uno.Themes.WinUI.Markup/Theme/NavigationView.cs
- src/library/Uno.Themes.WinUI.Markup/Theme/NavigationViewItem.cs
closes https://github.com/unoplatform/uno.themes-private/issues/5
> feat: add NavView lightweight styling brush resource markup

- src/library/Uno.Themes.WinUI.Markup/Theme/Button.cs
- src/library/Uno.Themes.WinUI.Markup/Theme/ComboBox.cs
- src/library/Uno.Themes.WinUI.Markup/Theme/PasswordBox.cs
- src/library/Uno.Themes.WinUI.Markup/Theme/RatingControl.cs
- src/library/Uno.Themes.WinUI.Markup/Theme/TextBox.cs
closes https://github.com/unoplatform/Uno.Themes/issues/1264
> fix: avoid duplicate ResourceKeyDefinitions

- src/library/Uno.Cupertino/Styles/Application/ColorPalette.xaml
- src/library/Uno.Cupertino/Styles/Controls/DatePicker.xaml
- src/library/Uno.Material/Styles/Application/v1/ColorPalette.xaml
- src/library/Uno.Material/Styles/Application/v2/SharedColorPalette.xaml
- src/library/Uno.Material/Styles/Controls/v1/DatePicker.xaml
- src/library/Uno.Material/Styles/Controls/v1/ToggleSwitch.xaml
- src/library/Uno.Material/Styles/Controls/v2/DatePicker.xaml
> fix: Shadow colors are no longer solid black

- doc/lightweight-styling.md
- doc/toc.yml
GitHub Issue: n/a
fix deadlinks to non-existing typography.md (shouldve been/was renamed textblock.md)
> docs: fix deadlinks

- src/library/Uno.Themes.WinUI.Markup/Uno.Themes.WinUI.Markup.csproj
@kazo0 This ensure we don't get an older version of Uno.WinUI via transitive dependency.
- Bugfix
- Feature
> build: Add explicit Uno.WinUI dependency to Themes Markup project

- src/samples/UWP/Uno.Themes.Samples.Skia.Gtk/Program.cs
> fix: Skia Deployment

- src/library/Uno.Material/Styles/Controls/v2/PasswordBox.xaml
﻿GitHub Issue: Internal
- Bugfix
https://github.com/unoplatform/uno.chefs/issues/710
> fix(passwordbox): content jumps when hover it

- doc/material-controls-extensions.md
- src/library/Uno.Material/Extensions/ControlExtensions.cs
- src/library/Uno.Material/Styles/Application/Common/Converters.xaml
- src/library/Uno.Material/Styles/Controls/v2/TextBox.xaml
- src/samples/UWP/Uno.Themes.Samples.Shared/Content/Controls/TextBoxSamplePage.xaml
- src/samples/UWP/Uno.Themes.Samples.Shared/Content/Controls/TextBoxSamplePage.xaml.cs
- src/samples/UWP/Uno.Themes.Samples.Shared/Content/Extensions/ControlExtensionsSamplePage.xaml
- src/samples/UWP/Uno.Themes.Samples.Shared/Content/Extensions/ControlExtensionsSamplePage.xaml.cs
- src/samples/UWP/Uno.Themes.Samples.Shared/Content/OverviewPage.xaml
- src/samples/UWP/Uno.Themes.Samples.Shared/Entities/Sample.cs
This reverts commit 0b2a7a98bca04d84285747390d046709347f335d.
﻿
> Revert "feat: Adding TextBox Icons Command and Visibility (#997)"

- src/library/Uno.Material/Styles/Controls/v2/Slider.xaml
- src/samples/UWP/Uno.Themes.Samples.Shared/Content/Controls/SliderSamplePage.xaml
﻿GitHub Issue: https://github.com/unoplatform/Uno.Themes/issues/1292
- Bugfix
|Before| After|
|--|--|
| <img width="209" alt="sliderBefore1" src="https://github.com/unoplatform/Uno.Themes/assets/34275909/c4e10f30-d602-4306-9273-157bfa1a675c">|<img width="208" alt="sliderAfter" src="https://github.com/unoplatform/Uno.Themes/assets/34275909/82276539-c9c6-4ae6-8509-bba31df5e1b0">|
|<img width="205" alt="sliderBefore2" src="https://github.com/unoplatform/Uno.Themes/assets/34275909/26e5093d-2613-4faf-8070-e1fa82a6a164">|<img width="213" alt="sliderAfter2" src="https://github.com/unoplatform/Uno.Themes/assets/34275909/edbaa29d-0a10-46b4-b833-df455f4132a5">|
- Commits must be following the …
> fix(slider): remove fixed space around slider

- doc/themes-overview.md
﻿Fixes #1279 
- 
Just a small fix
> Duplicated Word

- src/samples/UWP/Uno.Themes.Samples.Mobile/Uno.Themes.Samples.Mobile.csproj
- src/samples/UWP/Uno.Themes.Samples.Skia.Gtk/Uno.Themes.Samples.Skia.Gtk.csproj
- src/samples/UWP/Uno.Themes.Samples.Wasm/Uno.Themes.Samples.Wasm.csproj
- Other... Please describe: updating the sample's uno package
I updated the sample's uno package
> chore: update the samples uno package

- src/library/Uno.Material/Styles/Controls/v1/DatePicker.xaml
- src/library/Uno.Material/Styles/Controls/v2/DatePicker.xaml
﻿GitHub Issue: closes https://github.com/unoplatform/uno/issues/15193
- Bugfix
- Feature
> fix: Fix Material DatePicker down button not showing

- src/library/Uno.Cupertino/CupertinoResources.cs
- src/library/Uno.Cupertino/Styles/Controls/DatePicker.xaml
- src/library/Uno.Material/Styles/Controls/v1/DatePicker.xaml
- src/library/Uno.Material/Styles/Controls/v2/DatePicker.xaml
- src/library/Uno.Material/Styles/Controls/v2/_Resources.xaml
﻿GitHub Issue: closes https://github.com/unoplatform/Uno.Themes/issues/1331
- Bugfix
> fix: Fix DatePicker on Windows

- src/library/Uno.Material/Styles/Controls/v2/CommandBar.xaml
closes https://github.com/unoplatform/Uno.Figma/issues/2391
closes https://github.com/unoplatform/uno.chefs/issues/972
> fix: appbarbutton icon sizing

- doc/themes-control-extensions.md
- doc/toc.yml
> Update ControlExtesions to reflect breaking changes

- doc/styles/NavigationView.md
- src/library/Uno.Material/Styles/Controls/v2/NavigationView.xaml
- src/samples/UWP/Uno.Themes.Samples.Shared/Content/Controls/TopNavigationViewSamplePage_MUX.xaml
- src/samples/UWP/Uno.Themes.Samples.Shared/Content/Controls/TopNavigationViewSamplePage_MUX.xaml.cs
- src/samples/UWP/Uno.Themes.Samples.Shared/Uno.Themes.Samples.Shared.projitems
﻿GitHub Issue: closes #1317
- Bugfix
- Feature
> fix: Fix top navigation view foreground

- doc/material-getting-started.md
﻿## PR Type
Update Material resources links with proper aka links
> docs: Update Material resources links

- src/library/Uno.Cupertino/Styles/Controls/ProgressRing.xaml
- src/library/Uno.Cupertino/cupertino-common.props
- src/library/Uno.Material/Styles/Controls/v1/ProgressRing.xaml
- src/library/Uno.Material/Styles/Controls/v2/ProgressRing.xaml
- src/library/Uno.Material/material-common.props
- src/samples/WinUI/Directory.Build.props
> fix: fix progressring lottie source from uwp/winui split

- azure-pipelines.yml
- build/stage-determine-changes.yml
Adjustments after **https://github.com/unoplatform/Uno.Themes/pull/1374**
> ci: Adjustments for non docs only stages

- build/stage-determine-changes.yml
> ci: Adjust stage-determine-changes.yml

- doc/material-dsp.md
- doc/material-getting-started.md
﻿GitHub Issue: https://github.com/unoplatform/private/issues/443
1) Updates zip file to theme file (json)
2) Updates theme-builder URL to our AKA URL
> docs: update DSP refs

- .github/workflows/azure-static-webapp.yml
- PlatformItemGroups.props
- azure-pipelines.yml
- build/stage-build-android.yml
- build/stage-build-ios.yml
- build/stage-build-skia-gtk.yml
- build/stage-build-wasm.yml
- build/stage-build-windows.yml
- build/templates/dotnet-install-macos.yml
- build/templates/dotnet-install-windows.yml
- build/templates/dotnet-install.yml
- crosstargeting_override.props.sample
- src/library/Uno.Cupertino/Uno.Cupertino.WinUI.csproj
- src/library/Uno.Material.WinUI.Markup/Uno.Material.WinUI.Markup.csproj
- src/library/Uno.Material/Uno.Material.WinUI.csproj
- src/library/Uno.Themes.WinUI.Markup/Uno.Themes.WinUI.Markup.csproj
- src/library/Uno.Themes/Uno.Themes.WinUI.csproj
- src/library/tfm-common-uwp.props
- src/library/tfm-common-winui.props
- src/samples/Directory.Packages.props
- src/samples/UWP/Uno.Themes.Samples.Mobile/Uno.Themes.Samples.Mobile.csproj
- src/samples/UWP/Uno.Themes.Samples.Skia.Gtk/Uno.Themes.Samples.Skia.Gtk.csproj
- src/samples/UWP/Uno.Themes.Samples.Wasm/Uno.Themes.Samples.Wasm.csproj
- src/samples/WinUI/Directory.Build.props
- Build or CI-related changes
- Update to net8.0 to fix canary.
- Removing support for net7.
> build!: Update to net8.0 to fix canary

- src/library/Uno.Themes/Styles/Applications/Common/SharedColors.xaml
fixes #1422 
- Bugfix
Update OnSurfaceLowBrush to use LowOpacity instead of DisabledOpacity
> fix: Set OnSurfaceLowBrush to use LowOpacity

- PlatformItemGroups.props
This shouldn't be needed, and will be a trouble once Uno packaging restores the versions.
- Bugfix
- Feature
> build: Remove explicit `TargetPlatformVersion`

- doc/material-migration.md
> docs: Remove redundant spaces in sample code

- src/library/Uno.Material/Styles/Controls/v2/CommandBar.xaml
﻿GitHub Issue: closes #1462
- Bugfix
- Feature
> fix: Incorrect image resolution

- build/stage-build-skia-gtk.yml
> ci: Properly publish binlog for Gtk build

- src/samples/UWP/Uno.Themes.Samples.Skia.Gtk/Uno.Themes.Samples.Skia.Gtk.csproj
> build: Fix typo in Gtk UWP project

- src/library/Uno.Material/Styles/Application/Common/TextBoxVariables.xaml
- src/library/Uno.Material/Styles/Controls/v2/_Resources.xaml
﻿GitHub Issue: https://github.com/unoplatform/uno.hotdesign/issues/2225
- Bugfix
We were getting these warnings in HD. Turns out they are happening in all apps that use these resources.
> chore: fix and remove old resource keys

- doc/styles/AppBarButton.md
- doc/toc.yml
- src/library/Uno.Material/Styles/Controls/v2/AppBarButton.xaml
fixes https://github.com/unoplatform/private/issues/525
Introduce AppBarButtonHeight/Width theme resources
> fix: add missing resources for appbarbutton

- doc/lightweight-styling.md
Add Tech Bites video for lightweight styling
> docs: Add Tech Bites video for lightweight styling

- src/library/Uno.Cupertino/Styles/Controls/HyperlinkButton.xaml
- src/library/Uno.Material/Styles/Controls/v1/HyperlinkButton.xaml
- src/library/Uno.Material/Styles/Controls/v2/HyperlinkButton.xaml
﻿GitHub Issue: #1483
- Bugfix
- Feature
> fix: add underlining for HyperlinkButton on WinUI

- src/library/Uno.Material/Styles/Controls/v2/TextBox.xaml
﻿GitHub Issue: closes #1496
- Bugfix
> chore: adjust materialFilledTextBox layout

- src/library/Uno.Material/Styles/Controls/v2/Flyout.xaml
- src/library/Uno.Material/Styles/Controls/v2/_Resources.xaml
- src/samples/UWP/Uno.Themes.Samples.Shared/Content/Controls/FlyoutSamplePage.xaml
fixes https://github.com/unoplatform/Uno.Themes/issues/1508
Add new MaterialRadioMenuFlyoutItemStyle that matches the MaterialToggleMenuFlyoutItemStyle
> chore: add Material style for RadioMenuFlyoutItem

- src/library/Uno.Material/Styles/Controls/v2/Button.xaml
> fix: Wrap focus related states in a FocusStates vsg

- src/library/Uno.Material/Styles/Controls/v2/Slider.xaml
﻿GitHub Issue: https://github.com/unoplatform/uno.themes/issues/1536
- Bugfix
> fix(MediaTransportControls): MPE sliders vertical alignment

- src/library/Uno.Material/Styles/Controls/v2/MediaPlayerElement.xaml
GitHub Issue (If applicable): closes https://github.com/unoplatform/uno-private/issues/1378
- Bugfix
- Feature
> fix(mpe): foreground of MTC buttons become black on hover
