unoplatform/Uno.Themes

src/library/Uno.Material/Styles/Application/Colors.xaml
src/library/Uno.Material/Styles/Controls/Button.xaml
src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/ButtonSamplePage.xaml
src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/SamplesPage.xaml
src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/SamplesPage.xaml.cs

fix(colors):Properly use ThemeResources instead of StaticResource to enable changing the theme at runtime
GitHub Issue: #7 
- Bugfix
- Feature
Theme was not changing properly at runtime because StaticResources are not reevaluated.
- If the pull request contains breaking changes, commit message must contain a detailed description of the action to take for the consumer of this library. As …

fix(colors):Properly use ThemeResources

---

src/library/Uno.Material/Uno.Material.csproj
src/samples/Uno.Material.Samples/Uno.Material.Samples.UWP/Uno.Material.Samples.UWP.csproj

GitHub Issue: #9 
- Bugfix
Uno.UI is now installed in UWP for the library + bumped UAP to 17763 to be in line with Uno.

Fix problem where Uno wasn't available in the Uno.Material library and only in the UWP Sample

---

src/library/Uno.Material/Styles/Application/Colors.xaml
src/library/Uno.Material/Styles/Application/SelectionControlColors.xaml
src/library/Uno.Material/Styles/Controls/ComboBox.xaml

- Bugfix
Colors were off when looking at the app in dark mode for the Radio Button, CheckBox, ToggleSwitch and ComboBox samples.

Fix Darkmode colors : Radio Button, CheckBox, ToggleSwitch, ComboBox

---

src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/SamplesPage.xaml.cs

GitHub Issue: #120
- Bugfix
fixed nav-view loaded again on resume
NavigationView.Loaded event is proc'd every time the app is resumed from background. And, we just keep adding the entire list menu items again. _It seems that the listview isnt too happy when items with same contents (`Content, Icon, …

fix(droid): nav-view loaded again on resume

---

src/library/Uno.Material/Styles/Controls/CheckBox.xaml
src/library/Uno.Material/Styles/Controls/RadioButton.xaml

GitHub Issue: #102
- Bugfix
- Using transitions setters to avoid flickers on page loading a checked checkbox and radiobutton

fix(flicker): Using transitions setters to avoid flickers on page load

---

src/library/Uno.Material/Styles/Controls/ToggleSwitch.xaml
src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/ToggleSwitchSamplePage.xaml

﻿GitHub Issue: #442
- Bugfix
Make sure no space is used when the ToggleSwitch has no header

fix: ToggleSwitch shouldn't have an empty space if Header is not defined #442

---

src/library/Uno.Material/LinkerConfig.xml
src/library/Uno.Material/Uno.Material.csproj
src/samples/Uno.Material.Samples/Uno.Material.Samples.Shared/Content/Controls/TextBoxSamplePage.xaml
src/samples/Uno.Material.Samples/Uno.Material.Samples.Wasm/Program.cs

Fixes https://github.com/unoplatform/uno/issues/5122
The `ControlExtensions.Icon` attached property were linked-out by the linker, causing the value to be impossible to read in the control template.

fix(textbox_icon): The attached property were linked-out on Wasm

---

src/library/Uno.Material/Controls/ModalStandardBottomSheet.cs

﻿GitHub Issue: fixes https://github.com/unoplatform/Uno.Gallery/issues/137
- Bugfix
Modal sheet was initially visible when the window was resized.

fix: Make ModalStandardBottomSheet collapsed by default

---

src/library/Uno.Material/Styles/Controls/ProgressRing.xaml
src/library/Uno.Material/Uno.Material.csproj

closes #480
- Bugfix
Asset was not loading for UWP while using an Embedded Resource

fix: Add workaround to get Lottie animation files working for UWP

---

src/library/Uno.Material/Styles/Controls/ToggleSwitch.xaml

﻿GitHub Issue: #441
- Bugfix
Fix ToggleSwitch knob draggable range not covering the "perceived" end.

fix(toggleswitch): knob drag range

---

src/library/Uno.Material/Styles/Controls/ProgressRing.xaml
src/library/Uno.Material/Uno.Material.csproj

﻿GitHub Issue: https://github.com/unoplatform/Uno.Gallery/issues/174
- Bugfix
Fix the way we access the Lottie animation json filed for ProgressRing for UWP

fix(ProgressRing): Fix missing Lottie assets for UWP

---

src/library/Uno.Material/Styles/Controls/Card.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/CardSamplePage.xaml

closes #536
Add default ContentTemplates for Header/SubHeader/Supporting Templates - including default templates for Avatar/SmallMedia styles
Removes the need for defining your own Templates when simply presenting a TextBlock for things like Header/SubHeader
Before:
```xml
<controls:Card HeaderContent="Elevated card"
HeaderContentTemplate="{StaticResource HeaderTemplate}"
SubHeaderContent="With avatar"
SubHeaderContentTemplate="{StaticResource SubHeaderTemplate}"
AvatarContent="ms-appx:///Assets/Cards/Avatar.png"
AvatarContentTemplate="{StaticResource AvatarImageTemplate}"
MediaContent="ms-appx:///Assets/Cards/LargeMedia.png"
MediaContentTemplate="{StaticResource SampleImageTemplate}" …
```

refactor: Use default content templates in Material Card styles

---

src/library/Uno.Cupertino/Converters/StringFormatConverter.cs
src/library/Uno.Cupertino/CupertinoResources.cs
src/library/Uno.Cupertino/Styles/Application/Converters.xaml
src/library/Uno.Cupertino/Styles/Controls/Button.xaml
src/library/Uno.Cupertino/Styles/Controls/DatePicker.xaml
src/library/Uno.Cupertino/Uno.Cupertino.csproj
src/library/Uno.Material/Uno.Material.csproj
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Droid/Uno.Themes.Samples.Droid.csproj
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/App.xaml.Navigation.cs
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/DatePickerSamplePage.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/DatePickerSamplePage.xaml.cs
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Entities/Sample.cs
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Skia.Gtk/Uno.Themes.Samples.Skia.Gtk.csproj
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.UWP/Uno.Themes.Samples.UWP.csproj
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Wasm/Uno.Themes.Samples.Wasm.csproj
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.iOS/Uno.Themes.Samples.iOS.csproj
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.macOS/Uno.Themes.Samples.macOS.csproj

closes #470
https://github.com/unoplatform/Uno.Gallery/issues/195
- Feature
Add style for DatePickerFlyoutPresenter
Material:
Cupertino:

feat(DatePicker): Add Cupertino and Material DatePicker Styles

---

src/library/Uno.Cupertino/Styles/Controls/ComboBox.xaml

- Bugfix
Apps using the Cupertino ComboBox Style on UWP would crash since we are referencing the old name for the Cupertino Footnote TextBlock Style

fix(ComboBox): Use proper CupertinoFootnote style name

---

src/library/Uno.Material/Controls/BottomNavigationBar.cs

﻿GitHub Issue: https://stackoverflow.com/questions/67248286/uno-platform-bottomnavbar-uncheck-selected-item
- Bugfix
It is currently not possible to deselect all items in `BottomNavigationBar`

fix: Allow programmatically deselecting selected navigation bar item

---

src/library/Uno.Material/Styles/Controls/ToggleSwitch.xaml

﻿GitHub Issue: #574 
- Bugfix
Match Material Design guidelines for UWP and WASM regarding the ToggleSwitch control
https://material.io/components/switches
**Note for iOS regarding Material Design guidelines:**
It uses platform-specific switches on iOS instead of Material switches, as they have matching functionality and presentation.
**Note for Android:**
It uses Material switches with the ripple effect.
> If the pull request contains breaking changes, commit message must contain a detailed description of the action to take for the consumer of this library. As …

fix(ToggleSwitch): Match Material Design guidelines for UWP and WASM

---

src/library/Uno.Material/Controls/Ripple.cs

﻿GitHub Issue: https://github.com/unoplatform/uno/issues/5874
- Bugfix
Adjusted previous workaround (PR #443) in order to use PointerPoint.FrameId instead of creating and using a ripple handled property in addition to the PointerReleaseEvent that is not reliable in this case.
FrameId is used here to verify if a ripple has already occurred with this Id, to prevent the next on the line to ripple again with the same id, or to ripple again if it's a different one.
> If the pull request contains breaking changes, commit message must contain a detailed description of the action to take for the consumer of this …

fix(Ripple): Ripple should animate every time on WASM and not only the first time

---

src/library/Uno.Material/Styles/Controls/ComboBox.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ComboBoxSamplePage.xaml

﻿GitHub Issue: #596 
- Bugfix
- Correctly translate vertically the PlaceholderText when a value is selected for the ComboBox
- Manage to vertically center the content when a value is selected and there is no PlaceholderText
- Adjust the Outlined ComboBox Material style to match the guidelines
- Replace nonexisting resources for Cupertino ComboBox sample page so it can build in UWP
> If the pull request contains breaking changes, commit message must contain a detailed description of the action to take for the consumer of this library. As explained by the …

fix(ComboBox): Correctly translate PlaceholderText when a value is selected and adjust the outlined Material style to match the guidelines

---

src/library/Uno.Material/Styles/Controls/Button.xaml

﻿GitHub Issue: fixes #607
- Bugfix
- Feature
Adds a `VerticalContentAlignment="Center"` to the `ContentPresenter` of icons in Material buttons.

fix: vertically center icon in material buttons

---

src/library/Uno.Material/Styles/Controls/TextBox.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/TextBoxSamplePage.xaml

﻿GitHub Issue: #601 
- Bugfix
Correct the vertical content alignment of TexBox without a PlaceholderText using Material styles
- **BEFORE:**
- **AFTER:**

fix(ComboBox): Correct the vertical content alignment of TexBox without a PlaceholderText using Material styles

---

src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/DividerSamplePage.xaml.cs

﻿GitHub Issue: #606 
- Bugfix
Fix DividerSamplePage is not displaying on all platforms

fix(Divider): DividerSamplePage is not displaying on all platforms

---

src/library/Uno.Material/Controls/Chips/ChipGroup.cs
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ChipSamplePage.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Entities/Data/TestCollections.cs

﻿GitHub Issue: https://github.com/unoplatform/Uno.Themes/issues/624
- Bugfix
- Fixed ChipGroup not properly selecting when ItemsSource contains enums.
- Added sample:

fix: Fix ChipGroup not properly selecting when ItemsSource contains enums

---

src/library/Uno.Material/Controls/Chips/ChipGroup.cs

﻿GitHub Issue: https://github.com/unoplatform/Uno.Themes/issues/626
- Bugfix
- Allow ChipGroup initial section when ItemsSource is set after SelectedItem.

fix: Allow ChipGroup initial section when ItemsSource is set after SelectedItem

---

src/library/Uno.Material/Styles/Controls/TextBox.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/TextBoxSamplePage.xaml

- Bugfix
Changed opacity of disabled MaterialFilledTextBoxStyle and MaterialOutlinedTextBoxStyle to match Material Design.
Added placeholders to disabled sample in order to see the full disabled version.
For some reason the brush's opacity isn't translated to the ScrollViewer's opacity so I changed it directly.
Screenshots: …

Fix TextBox Disabled colors

---

src/library/Uno.Material/Controls/Ripple.cs
src/library/Uno.Material/Styles/Controls/Ripple.xaml

﻿GitHub Issue: closes #627
- Bugfix
Fix an issue where the rippling animation of Ripple control were too fast to be observed.
RippleSizeMultiplier is reduced to 2 from 8, as it also is a multiplier for how fast the ripple is travelling if we only consider the visible area, not whats outside. The …

fix(ripple): animation speed

---

src/library/Uno.Material/Converters/ToUpperConverter.cs
src/library/Uno.Material/Styles/Controls/Button.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ButtonSamplePage.xaml

- Bugfix
Material styled Buttons will have their Content capitalized by default

fix: Auto-Capitalize Material Button Content

---

src/library/Uno.Material/Styles/Application/ColorPalette.xaml
src/library/Uno.Material/Styles/Controls/ToggleSwitch.xaml

﻿GitHub Issue: unoplatform/nventive-private#320
- Bugfix
You are no longer required to redefine the follow resource in color override:
- `MaterialToggleSwitchButtonColor`
- `MaterialToggleSwitchBackgroundColor`
They will now be based on the material colors. …

refactor: color overriding for ToggleSwitch

---

src/library/Uno.Material/Extensions/ControlExtensions.cs
src/library/Uno.Material/Styles/Controls/ToggleButton.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Extensions/ControlExtensionsSamplePage.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Extensions/ControlExtensionsSamplePage.xaml.cs

GitHub Issue: https://github.com/unoplatform/uno.ui.toolkit/issues/81
- Feature
Add ControlExtensions.AlternateContent and MaterialToggleButtonIconStyle

feat: Add ControlExtensions.AlternateContent and MaterialToggleButtonIconStyle

---

src/library/Uno.Material/Styles/Controls/NavigationView/WUX/NavigationView.xaml
src/library/Uno.Material/Styles/Controls/NavigationView/WUX/NavigationView_SplitView.xaml

- Bugfix
The WUX `NavigationView` styles overrides the default `SplitView` style on Android and iOS, which then applies this "drawer-based" split view even to MUX `NavigationView` which is then broken (as `Compact` pane mode is enabled there).

fix: Don't override default SplitView style when not explicitly requested

---

src/library/Uno.Material/Styles/Controls/Flyout.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/App.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/FlyoutSamplePage.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/FlyoutSamplePage.xaml.cs

BREAKING CHANGE: `MaterialFlyoutPresenterStyle ` was changed for `MaterialContentFlyoutPresenterStyle` and a new `MaterialFlyoutPresenterStyle` was added in order to have fullscreen, modal centered, and bottom sheet Flyout
﻿GitHub Issue: #685 
- Feature
Add a MaterialFlyoutPresenterStyle that will help to have:
- a FullScreen Flyout
- a Modal centered Flyout
- a Bottom sheet Flyout
Related issue in Uno : https://github.com/unoplatform/uno/issues/7534

Add a MaterialFlyoutPresenterStyle that will help to have fullscreen, modal centered and bottom sheet Flyout

---

README.md
src/library/Uno.Material/Styles/Controls/Button.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ButtonSamplePage.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/OverviewPage.xaml

﻿GitHub Issue: https://github.com/unoplatform/uno.toolkit.ui/issues/166
- Bugfix
Add missing MaterialButtonIconStyle for Uno.Material

fix(Button): Add missing MaterialButtonIconStyle

---

src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Droid/Uno.Themes.Samples.Droid.csproj

- Android project file changes
- Remove workarounds not needed anymore as their related issues are now fixed:
- Enable again AndroidUseAapt2 as https://github.com/unoplatform/uno/issues/1382 is now resolved
- Remove the target that will force the generation of the APK as it's not needed anymore and as it causes issues to deploy on Android with latest VS 2022 Prev 17.1.0 Preview 1.0 and 1.1
- Enabling again Fast Deployment by default for Debug as when disabled this cause issues to deploy on Android with latest VS 2022 Prev 17.1.0 Preview 1.0 and 1.1 
(Related issues : https://github.com/xamarin/xamarin-android/issues/6480 / https://developercommunity.visualstudio.com/t/cannot-debug-on-android/1590528)
Please check if your PR fulfills the …

chore(Android): Remove workarounds not needed anymore and enabling again Fast Deployment

---

src/library/Uno.Material/Styles/Controls/ComboBox.xaml

﻿GitHub Issue: closes #701
- Feature
Instead of forcing the default combo box border brush onto the elevated view, we instead set it as default and let the templated parent set its own border brush.

feat: use templated parent border brush on combo box's elevated view

---

Directory.Build.props
Directory.Build.targets
build/stage-build.yml
src/library/Uno.Cupertino/Uno.Cupertino.csproj
src/library/Uno.Material/Uno.Material.csproj

Removes MonoAndroid 10.0 which is not available anymore with the Play Store.

ci: Adjust for Uno 4.1 and Android 12

---

Uno.Themes.sln

Themes SampleApp `Debug|Android` and `Release|Android` build configs should not build Skia.Gtk or macOS heads

Don't build Skia.GTK/macOS heads for Android config

---

src/library/Uno.Cupertino/Generated/mergedpages.xaml
src/library/Uno.Material/Generated/mergedpages.xaml
src/library/Uno.Material/Styles/Controls/TextBox.xaml

- Bugfix
`TextBox` and `PasswordBox` may have different heights with `Uno.Material 1.4.0-dev.17` with a custom font and some custom font size settings even if they are configured the exact same way. They also have different button alignments.
Before when height is not manually set:
Before when height is manually set:
After: …

fix: Made TextBox uniform with PasswordBox.

---

src/library/Uno.Material/Styles/Controls/CheckBox.xaml
src/library/Uno.Material/Styles/Controls/Flyout.xaml

closes https://github.com/unoplatform/nventive-private/issues/357
- Bugfix
Two resources existed in Uno.Material with the key `CheckGlyphPathStyle`, one in `CheckBox.xaml` and one in `Flyout.xaml`. As a result of the XamlMerge, there can be only one true CheckGlyphPathStyle so the Flyout Path Data was being used for the CheckBox's Check Glyph data

fix(CheckBox): Avoid resource name clash for Path Data resources with xamlmerge

---

src/library/Uno.Material/Generated/mergedpages.xaml
src/library/Uno.Material/Styles/Controls/PasswordBox.xaml
src/library/Uno.Material/Styles/Controls/TextBox.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/PasswordBoxSamplePage.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/TextBoxSamplePage.xaml

﻿GitHub Issue: #724 #603
- Bugfix
Added animation to delete text button for Textbox, plus some layout rework
https://github.com/unoplatform/Uno.Themes/issues/724

fix: [Material][Textbox] Add press state to delete button

---

src/library/Uno.Material/Generated/mergedpages.v2.xaml
src/library/Uno.Material/Styles/Controls/v2/Button.xaml

﻿GitHub Issue: https://github.com/unoplatform/Uno.Figma/issues/602
- Bugfix
Fix MaterialOutlinedButtonStyle default background and disabled state to match Material M3 guidelines and Uno Figma file

fix: MaterialOutlinedButtonStyle default background and disabled state

---

src/library/Uno.Material/Styles/Application/v2/SharedColorPalette.xaml

Match colors from https://www.figma.com/file/trM3i5qUPmFBcnxWXXmnuF/Uno-Platform-Material-Toolkit-R2?node-id=418%3A11559

fix: Fix incorrect surfacevariant colors

---

src/library/Uno.Material/MaterialResourcesV2.cs
src/library/Uno.Material/Styles/Controls/v2/ProgressRing.xaml

WinUI 3 currently does not support the [DeterminateSource](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.progressring.determinatesource?view=winui-2.8-prerelease) and [IndeterminateSource](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.progressring.indeterminatesource?view=winui-2.8-prerelease) properties. These properties are needed for the Material style. So we should not include the ProgressRing Material styles when running a Windows WinUI 3.
WinUI Uno platforms support the DeterminateSource and IndeterminateSource so we only need to remove the ProgressBar for Windows WinUI 3

fix: Only remove ProgressRing for Windows WinUI3 platforms

---

src/library/Uno.Material/Styles/Controls/v2/TextBlock.xaml

﻿GitHub Issue: [#613](https://github.com/unoplatform/Uno.Figma/issues/613)
- Bugfix
Fix Textblock typo style to match latest Uno Figma file version

fix: Textblock typo style to match latest Uno Figma file version

---

src/library/Uno.Material/Styles/Controls/v1/PasswordBox.xaml

closes https://github.com/unoplatform/nventive-private/issues/400
- Bugfix
PasswordBox's RevealButton should prevent itself from being clicked while in the ButtonCollapsed Visual State

fix(PasswordBox): Make v1 PasswordBox reveal button unclickable when hidden

---

src/library/Uno.Material/Styles/Controls/v1/Flyout.xaml
src/library/Uno.Material/Styles/Controls/v2/Flyout.xaml

﻿GitHub Issue: closes unoplatform/uno#9231
- Bugfix
- fix MenuFlyout crash when opened
- fix MenuFlyoutItem crash when moused over
MenuFlyout is due to wrong value type being set to `MenuFlyoutPresenter.CharacterSpacing` (of type `int`)
MenuFlyoutItem is due to SolidColorBrush being used instead, …

fix(winui): MenuFlyout&Item crashes

---

doc/material-controls-styles.md
src/library/Uno.Material/Generated/mergedpages.v2.xaml
src/library/Uno.Material/MaterialResourcesV2.cs
src/library/Uno.Material/Styles/Controls/v2/ContentDialog.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ContentDialogSamplePage.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ContentDialogSamplePage.xaml.cs
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Controls/SamplePageLayout.cs
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Uno.Themes.Samples.Shared.projitems

﻿GitHub Issue: resolved #637
- Bugfix
- Feature
Added material style and sample for ContentDialog
fixed an issue where when only M3MaterialTemplate is specified, the SamplePageLayout would not display anything beside page header/footer.

feat: added material style for ContentDialog

---

src/library/Uno.Material/Generated/mergedpages.v2.xaml
src/library/Uno.Material/Styles/Controls/v2/ComboBox.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ComboBoxSamplePage.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ComboBoxSamplePage.xaml.cs
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Entities/Data/TestCollections.cs

﻿GitHub Issue: #848 
- Bugfix
Fixed Material ComboBoxItem not working when using a custom ItemTemplate

fix: Material ComboBoxItem not working when using a custom ItemTemplate

---

src/library/Uno.Material/Styles/Controls/v2/ToggleButton.xaml

﻿GitHub Issue: closes #850 
What kind of change does this PR introduce? 
- Bugfix 
Was not allowing overriding corner radius in Toggle Button 

fix: add cornerradius to toggle button

---

src/library/Uno.Material/Generated/mergedpages.v2.xaml
src/library/Uno.Material/MaterialResourcesV2.cs
src/library/Uno.Material/Styles/Controls/v2/NavigationView.xaml
src/library/Uno.Material/Styles/Controls/v2/ToggleSwitch.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Shell.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Shell.xaml.cs
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Skia.Gtk/Uno.Themes.Samples.Skia.Gtk.csproj

﻿GitHub Issue: resolved #856
- Bugfix
- the following properties of the NavigationView should now display correctly: PaneCustomContent, PaneFooter, FooterMenuItems, IsSettingsVisible
- added a new `MaterialPaddedNavigationViewStyle`(alias: `PaddedNavigationViewStyle`) that will dynamically adjust padding for content in "Minimal" mode …

fix: NavigationView material style footer

---

src/library/Uno.Material/Styles/Controls/v2/ToggleSwitch.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/ToggleSwitchSamplePage.xaml

﻿GitHub Issue: resolved: #857
- Bugfix
MaterialToggleSwitchStyle:
- On non-mobile platforms, the thumb will not be properly vertically aligned when the control height is set to a value different than the default of 40.
- On mobile platforms, the header content is stacked vertically on top of the toggle, as opposed to other platforms where this is stacked horizontally to the left. In addition, the configured material font is not properly applied on the header.
> If the pull request contains breaking changes, commit message must contain a detailed description of …

MaterialToggleSwitchStyle fixes

---

src/library/Uno.Material/Styles/Controls/v2/NavigationView.xaml

﻿GitHub Issue: re: #856
- Bugfix
MaterialNavigationViewStyle (v2) is referencing non-existent v1 mux resources, and crashes on windows head.

fix(NavigationView): invalid resource references

---

Directory.Build.props

Addresses https://developercommunity.visualstudio.com/t/XamarinMac-binaries-are-missing-in-173/10164443

ci: add xamarin.mac workaround

---

src/library/Uno.Material/Styles/Controls/v2/ComboBox.xaml

﻿GitHub Issue: #848
- Bugfix
`ComboBox.ItemTemplateSelector` only works for the unopened selected item, but not for the `ComboBoxItem`s found in the dropdown.
Continuation of #848 with `ItemTemplate`, we fixed that but forgot `ItemTemplateSelector`...

fix(CBI): template-selector not being applied

---

src/library/Uno.Themes.WinUI.Markup/AssemblyInfo.cs
src/library/Uno.Themes.WinUI.Markup/ResourceValue.cs
src/library/Uno.Themes.WinUI.Markup/Theme.Brushes.cs
src/library/Uno.Themes.WinUI.Markup/Theme.Colors.cs
src/library/Uno.Themes.WinUI.Markup/Theme.Styles.cs
src/library/Uno.Themes.WinUI.Markup/Uno.Themes.WinUI.Markup.csproj

- Feature
Provide the full resource key as a string for whichever resource we are trying to build. This could be useful in cases where we may want to make use of [StaticResource.Get<T>(string key)]
[Theme Markup extensions should expose the resource key …

feat: markup extensions exposing resource keys

---

src/library/Uno.Material.WinUI.Markup/AssemblyInfo.cs
src/library/Uno.Material.WinUI.Markup/MarkupInit.cs
src/library/Uno.Material.WinUI.Markup/Uno.Material.WinUI.Markup.csproj
src/library/Uno.Themes.WinUI.Markup/AssemblyInfo.cs
src/library/Uno.Themes.WinUI.Markup/ResourceValue.cs
src/library/Uno.Themes.WinUI.Markup/Theme.Brushes.cs
src/library/Uno.Themes.WinUI.Markup/Theme.Colors.cs
src/library/Uno.Themes.WinUI.Markup/Theme.Styles.cs
src/library/Uno.Themes.WinUI.Markup/Uno.Themes.WinUI.Markup.csproj

﻿GitHub Issue: n/a
- Other Update Markup Libraries
Updates Markup Generator and Uno.WinUI.Markup. The Markup Libraries have a breaking namespace change. This also updates the MarkupInit to be in the correct Uno.Material namespace as there should not have been an Uno.Material.WinUI.Markup namespace.

update markup libraries

---

src/library/Uno.Cupertino/Uno.Cupertino.csproj

Disables trimming on OSX+Mono combination for test apps only to avoid:
```
/Users/runner/.nuget/packages/uno.ui/4.7.0-dev.900/buildTransitive/Uno.UI.Tasks.targets(156,3): error MSB4216: Could not run the "LinkerDefinitionMergerTask_v6233eb01169e7267991cb814d9262815cb867772" task because MSBuild could not create or connect to a task host with runtime "CLR4" and architecture "x64".  Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "/Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/MSBuild.exe" exists and can be run. [/Users/runner/work/1/s/src/library/Uno.Cupertino/Uno.Cupertino.csproj]
```

fix: Disable trimming on osx+mono combination

---

src/library/Uno.Material/Extensions/ResourceDictionaryExtensions.cs
src/library/Uno.Material/MaterialColorsV2.cs
src/library/Uno.Material/MaterialFonts.cs
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/App.xaml

﻿GitHub Issue: closes #907
- Bugfix
fix "Element is already a child of another element" windows crash when attempting to merge font/color override res-dict multiple times

fix(win): resource initialization crash

---

src/library/Uno.Material.WinUI.Markup/MarkupInit.cs
src/library/Uno.Material/MaterialColors.cs
src/library/Uno.Material/MaterialColorsV2.cs
src/library/Uno.Material/MaterialFonts.cs
src/library/Uno.Material/MaterialResources.cs
src/library/Uno.Material/MaterialResourcesV2.cs
src/library/Uno.Material/MaterialTheme.cs
src/library/Uno.Material/Styles/Controls/v2/_Resources.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/App.xaml

closes https://github.com/unoplatform/Uno.Themes/issues/822
- Feature
We can now init the Material resources, including the fonts and colors by doing this:
```xml
<Application ...>
<Application.Resources>
<ResourceDictionary>
<ResourceDictionary.MergedDictionaries>
<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
<MaterialTheme xmlns="using:Uno.Material"
ColorOverrideSource="ms-appx:///ColorPaletteOverride.xaml"
FontOverrideSource="ms-appx:///MaterialFontsOverride.xaml" />
</ResourceDictionary.MergedDictionaries>
</ResourceDictionary>
</Application.Resources>
</Application>
```
And for C# Markup:
```cs
public static T UseMaterial<T>(this T app,
ResourceDictionary colorOverride = null,
ResourceDictionary fontOverride = null) …
```

feat: Add new MaterialTheme for simpler init

---

src/library/Uno.Material/Styles/Controls/v2/CommandBar.xaml

closes https://github.com/unoplatform/Uno.Themes/issues/914
- Bugfix
Add [this workaround](https://github.com/microsoft/microsoft-ui-xaml/issues/6388) for the `CommandBarExtensions.MainCommand` attached property. Avoids a crash on WinUI

fix: Add workaround for Material CommandBar NavigationCommand extension

---

src/library/Uno.Cupertino/Uno.Cupertino.csproj
src/library/Uno.Material.WinUI.Markup/Uno.Material.WinUI.Markup.csproj
src/library/Uno.Material/Uno.Material.csproj
src/library/Uno.Themes.WinUI.Markup/Uno.Themes.WinUI.Markup.csproj

- Bugfix
Referencing Material from WinUI project requires updating frameworkreference - this shouldn't be required

fix: Removing framework references

---

src/library/Uno.Cupertino/Uno.Cupertino.csproj
src/library/Uno.Material/Uno.Material.csproj

- Bugfix
Unnecessary forcing to v1.2 of winappsdk. This PR reverts back to 1.1.0 whilst keeping latest build tools version

fix: Reverting winappsdk version

---

src/library/Uno.Material/Styles/Application/v2/Typography.xaml

Fixes https://github.com/unoplatform/Uno.Figma/issues/1312
Following design requirements

fix(fontsweight): Fix LabelExtraSmallFontWeight should be "400", not 500

---

src/library/Uno.Themes.WinUI.Markup/Theme.Colors.cs

- closes #970 
- Bugfix
Adds missing Theme ResourceValues for Color Overrides

Add missing ResourceValues for C# Markup

---

src/library/Uno.Material/Uno.Material.csproj

Brings in the fix from https://github.com/unoplatform/uno.fonts/pull/31, which is a source of pain and hard to debug. See https://github.com/unoplatform/Uno.Gallery/pull/739 for example.
cc @Xiaoy312 @kazo0

fix: Update Roboto package to 2.2.2 so that it works correctly on Linux

---

src/library/Uno.Material/Styles/Controls/v1/TextBox.xaml

- Feature
In this pr, I removed this
Because the fact that the KeyFrame 0 starts with Opacity="1" makes the clear button appear when first loading a page with a textbox then disapears when it's opacity is set to 0 200 milliseconds after. By removing it we keep the desired behaviour of disapearing after 200 milliseconds when the focus is lost but without the flickering when first loading the page. I remove the lines from MaterialOutlinedTextBoxStyle and MaterialFilledTextBoxStyle since both had the same animation.
Please check if your PR fulfills the …

fix: textbox clear button flickering on first load

---

src/library/Uno.Material/Styles/Controls/v2/PasswordBox.xaml
src/samples/Uno.Themes.Samples/Uno.Themes.Samples.Shared/Content/Controls/PasswordBoxSamplePage.xaml

closes #989 
Applies lightweight styling to the PasswordBox control.
Locally overridden with

refactor: Add lightweight styling resources for Material PasswordBox

---

src/library/Uno.Material/Styles/Controls/v2/RadioButton.xaml

﻿GitHub Issue: closes #991 
Locally overriden with:
```
<SolidColorBrush x:Key="RadioButtonForeground" Color="Red" />
<SolidColorBrush x:Key="RadioButtonForegroundPointerOver" Color="Yellow" />
<SolidColorBrush x:Key="RadioButtonForegroundPressed" Color="Green" />
<SolidColorBrush x:Key="RadioButtonForegroundDisabled" Color="Orange" />
<SolidColorBrush x:Key="RadioButtonOuterEllipseStroke" Color="Red" />
<SolidColorBrush x:Key="RadioButtonOuterEllipseStrokePointerOver" Color="Orange" />
<SolidColorBrush x:Key="RadioButtonOuterEllipseStrokePressed" Color="Yellow" />
<SolidColorBrush x:Key="RadioButtonOuterEllipseStrokeDisabled" Color="Green" /> …
```

refactor: add lightweight styling resources for radiobutton

---

src/library/Uno.Material/Styles/Application/v2/SharedColors.xaml
src/library/Uno.Material/Styles/Controls/v2/TextBox.xaml

closes #988 
﻿GitHub Issue: #988
TextBox.xaml has been modified. New resources have been created for overriding in other pages.
Filled
Outlined
Locally overridden with:
<Page.Resources>
<SolidColorBrush x:Key="FilledTextBoxBackground"
Color="Red" />
<SolidColorBrush x:Key="FilledTextBoxBackgroundPointerOver"
Color="Orange" />
<SolidColorBrush x:Key="FilledTextBoxBackgroundFocused"
Color="Yellow" />
<SolidColorBrush x:Key="FilledTextBoxBackgroundDisabled"
Color="Green" />
<SolidColorBrush x:Key="FilledTextBoxBorderBrush"
Color="Blue" />
<SolidColorBrush x:Key="FilledTextBoxBorderBrushPointerOver"
Color="Indigo" />
<SolidColorBrush x:Key="FilledTextBoxBorderBrushFocused"
Color="Pink" /> …

refactor(textbox): Add the Lightweight Styling Text Box Style

---

src/library/Uno.Material/Styles/Controls/v1/CheckBox.xaml

closes #823 
﻿GitHub Issue: #823 
- Bugfix
The ContentPresenter foreground is now templatebound to Foreground. The brush of Foreground has been changed, and the fills of glyphs are now given a brush instead of being templatebound.
As of this instant when this PR is created, the master branch of Uno.Themes is crashing, and this branch has been created from the master branch.

fix: foreground of ContentPresenter is templatebounded

---

src/library/Uno.Material/Styles/Controls/v2/NavigationView.xaml

closes #1019﻿
GitHub Issue: #1019
Overriden:
Overriden with:
<Page.Resources>
<SolidColorBrush x:Key="NavigationViewBackground" Color="Red" />
<SolidColorBrush x:Key="NavigationViewDefaultPaneBackground" Color="Orange" />
<SolidColorBrush x:Key="NavigationViewPaneBackground" Color="Yellow" />
<SolidColorBrush x:Key="NavigationViewDefaultPaneBorderBrush" Color="Green" />
<SolidColorBrush x:Key="NavigationViewButtonForeground" Color="Blue" />
<SolidColorBrush x:Key="NavigationViewButtonForegroundPointerOver" Color="Indigo" />
<SolidColorBrush x:Key="NavigationViewButtonForegroundPressed" Color="Pink" />
<SolidColorBrush x:Key="NavigationViewButtonForegroundDisabled" Color="Red" /> …

refactor(navigationview): Add lightweight styling to navigation view style (mux)

---

src/library/Uno.Material/Styles/Controls/v2/RatingControl.xaml
src/library/Uno.Material/Styles/Controls/v2/_Resources.xaml
src/samples/UWP/Uno.Themes.Samples.Shared/Content/Controls/RatingControlSamplePage.xaml
src/samples/UWP/Uno.Themes.Samples.Shared/Content/Controls/RatingControlSamplePage.xaml.cs
src/samples/UWP/Uno.Themes.Samples.Shared/Uno.Themes.Samples.Shared.projitems

closes #830 
﻿GitHub Issue: #830 
- Bugfix
- Feature
Added RatingControl styles in v2/ and RatingControl Sample Page.
Overriden:
Overriden with:
<Page.Resources>
<SolidColorBrush x:Key="RatingControlForeground"
Color="Red" />
<SolidColorBrush x:Key="RatingControlForegroundUnselected"
Color="Orange" />
<SolidColorBrush x:Key="RatingControlForegroundSelected"
Color="Yellow" />
<SolidColorBrush x:Key="RatingControlPlaceholderForeground"
Color="Green" />
<SolidColorBrush x:Key="RatingControlPlaceholderForegroundPointerOver"
Color="Blue" />
<SolidColorBrush x:Key="RatingControlForegroundPointerOverUnselected"
Color="Indigo" />
<SolidColorBrush x:Key="RatingControlForegroundPointerOverSelected"
Color="Pink" /> …

feat(ratingcontrol): Add Rating Control Styles and Rating Control Sample Page

---

src/library/Uno.Material/Styles/Controls/v2/DatePicker.xaml

﻿GitHub Issue: #1006 #1067
- Refactoring DatePicker styles and moving them into ResourceDictionary.

refactor(DatePicker): lightweight styling for datepicker

---

src/library/Uno.Material/Styles/Controls/v2/RadioButton.xaml

﻿GitHub Issue: #991 #1067
- Refactors non-brush resources for lightweight styling.

refactor(RadioButton): lightweight styling radiobutton

---

src/library/Uno.Material/Styles/Application/Common/Converters.xaml
src/library/Uno.Material/Styles/Controls/v2/ToggleButton.xaml
src/samples/UWP/Uno.Themes.Samples.Shared/Content/Extensions/ControlExtensionsSamplePage.xaml

﻿GitHub Issue: #1132
- Bugfix
Adds a fallback value and target null value for AlternateContent binding
- ~~[ ] Tested MacOS~~
https://github.com/unoplatform/Uno.Themes/issues/1132

fix: Fix AlternateContent for ToogleButton crashing on UWP when not set

---

src/samples/UWP/Uno.Themes.Samples.UWP/Uno.Themes.Samples.UWP.csproj

Disables unused .NET native for UWP sample builds

ci(perf): Disable .NET native for uwp builds

---

src/library/Uno.Themes.WinUI.Markup/Theme.Styles.cs
src/library/Uno.Themes.WinUI.Markup/Theme/ToggleSwitch.cs

﻿GitHub Issue: [Lightweight styling - ToogleSwitch](https://github.com/unoplatform/uno.themes-private/issues/2)
- Feature
add lightweight styling resources to ToggleSwitch

feat: add lightweight styling resources to ToggleSwitch

---

src/library/Uno.Themes.WinUI.Markup/Theme.Styles.cs
src/library/Uno.Themes.WinUI.Markup/Theme/TextBox.cs

﻿GitHub Issue:[ unoplatform/uno.themes-private#12](https://github.com/unoplatform/uno.themes-private/issues/12)
- Feature
add lightweight styling TextBox

feat: add lightweight styling to TextBox

---

doc/material-controls-styles.md
doc/styles/TextBox.md

Setting `OutlinedTextBoxStyle` as default instead of `FilledTextBoxStyle` in the docs.

docs: Updating OutlinedTextBoxStyle as default

---

src/library/Uno.Themes.WinUI.Markup/Theme.Styles.cs
src/library/Uno.Themes.WinUI.Markup/Theme/Slider.cs
src/library/Uno.Themes.WinUI.Markup/Theme/ToggleButton.cs

﻿GitHub Issue: https://github.com/unoplatform/uno.themes-private/issues/3
- Feature

feat: add lightweight styling resources to ToggleButton

---

src/library/Uno.Cupertino/Styles/Controls/ToggleSwitch.xaml
src/library/Uno.Material/Styles/Controls/v2/ToggleSwitch.xaml

﻿GitHub Issue: #1225
- Bugfix
Added `<x:Double x:Key="ToggleSwitchThemeMinWidth">0</x:Double>` and `<Setter Property="MinWidth" Value="{ThemeResource ToggleSwitchThemeMinWidth}" />` to prevent the extra `MinWidth="154"` from stretching the control.

fix(ToggleSwitch): Override ToggleSwitch MinWidth

---

doc/material-colors.md
src/library/Uno.Material/Styles/Application/v2/SharedColorPalette.xaml

GitHub Issue: fixes #1143
- Bugfix
Fix OnSecondaryContainerColor for Light Theme to match default Material colors and Figma file
(cf. https://github.com/unoplatform/Uno.Themes/issues/1143#issuecomment-1777892347)

fix: OnSecondaryContainerColor for Light Theme to match default Material colors and Figma file

---

doc/lightweight-styling.md

closes https://github.com/unoplatform/uno.themes-private/issues/15

docs: add markup section for lightweight styling

---

doc/material-getting-started.md
src/library/Uno.Material.WinUI.Markup/MarkupInit.cs

Refactor MarkupInit helper class to use with ResourceDictionaryBuilder, new syntax is:
```cs
this.Build(r => r.UseMaterial(
new Styles.ColorPaletteOverride(),
new Styles.MaterialFontsOverride()));
```

feat: add material markup helper and docs

---

src/library/Uno.Cupertino/Uno.Cupertino.csproj
src/library/Uno.Material/Uno.Material.csproj

1.2.0 generates this warning:
`##[warning]src\library\Uno.Material\Uno.Material.csproj(0,0): Warning NU1603: Uno.Material.WinUI depends on Microsoft.WindowsAppSDK (>= 1.2.0) but Microsoft.WindowsAppSDK 1.2.0 was not found. An approximate best match of Microsoft.WindowsAppSDK 1.2.221109.1 was resolved.`

fix: use valid winappsdk version

---

src/library/Uno.Material/Styles/Application/v2/Typography.xaml
src/library/Uno.Material/Styles/Controls/v2/TextBlock.xaml

﻿GitHub Issue: closes #1250 
- Bugfix
Add overridable font-family resources for each of typography textblock styles.

fix: FontFamilyOverride

---

src/library/Uno.Material/Styles/Application/v2/Typography.xaml

fixes #1281 
- Bugfix
Add overridable font-family resources for each of typography textblock styles.

fix: FontFamilyOverride-2

---

src/library/Uno.Material/Styles/Controls/v2/ToggleButton.xaml

﻿GitHub Issue: 
- Bugfix
|Before|After|
|--|--|
|![togglebutton-broken](https://github.com/unoplatform/Uno.Themes/assets/34275909/8167f189-4b06-44ad-aaeb-06d9a5a88f2c)|![togglebutton-fixed](https://github.com/unoplatform/Uno.Themes/assets/34275909/6ad4f735-0b78-43e0-bb3c-dbd3b4e75f44)|

fix(alternateContent): fix toggleButton alternate content visual states

---

src/library/Uno.Material/Styles/Controls/v2/ListView.xaml

﻿GitHub Issue: close https://github.com/unoplatform/Uno.Themes/issues/1291
- Bugfix
The check symbol is not showing in the ListView. 
- [] UWP

fix: checkbox issue in ListView

---

src/samples/UWP/Uno.Themes.Samples.Shared/Content/Controls/FabSamplePage.xaml

- Bugfix
Changed the small styles to the default styles in the default section of the fab sample page

fix: show default sized fabs in sample page

---

src/library/Uno.Material/Styles/Controls/v2/TextBox.xaml

﻿GitHub Issue: closes #1334 
- Bugfix
This PR aligns the Outlined style of the TextBox to the Filled TextBox style and the PasswordBox style for consistency in the alignment of the TextBox components (icon, text, placeholder).
Before and after screenshots are available in issue #1334.

fix: TextBox Outlined style inconsistencies

---

build/templates/dotnet-install-macos.yml
build/templates/dotnet-install-windows.yml

This change will bump to 7.0.401's workloads, in order to align with recent Uno 5.1 changes.

chore: Bump to later net7 builds

---

src/library/Uno.Material/Styles/Controls/v2/Button.xaml
src/library/Uno.Material/Styles/Controls/v2/FloatingActionButton.xaml

closes https://github.com/unoplatform/uno/issues/14633
closes #1293 
- Bugfix
Move Focused visual state into CommonStates VisualStateGroup to avoid conflicts between the FocuseStates and the CommonStates when an element is Focused and then becomes Disabled.
This sort of VisualState organization can be seen in the [Fluent styles as well](https://github.com/unoplatform/uno/blob/095d213ab1143dc2799c289696123102db7c13e0/src/Uno.UI.FluentTheme.v2/Resources/Version2/Priority02/PasswordBox_themeresources.xaml#L196).

fix: move Focused visualstate to CommonStates group

---

src/library/Directory.Packages.props
src/library/Uno.Themes.WinUI.Markup/Uno.Themes.WinUI.Markup.csproj

chore: bump uno.winui.markup to 5.2

---

src/library/Uno.Material/Styles/Controls/v2/TextBox.xaml

related https://github.com/unoplatform/Uno.Themes/issues/1379
- Bugfix
The PlaceholderText should be using the BodyLarge typography values, same as the TextBox's Content element. For now, until https://github.com/unoplatform/Uno.Themes/pull/1014 is merged, we will also keep those typorgaphy values when the PlaceholderElement is translated to serve as the "header"/"label" of the TextBox and keep it scaled down to the same size as BodySmall

fix: Use BodyLarge typography for TextBox Placholder

---

Uno.Themes.sln
build/templates/canary-updater.yml

﻿GitHub Issue: https://github.com/unoplatform/uno.themes-private/issues/28
Update canary updater and adjust samples path for UWP to fix canary build

chore: Update canary updater and adjust samples path for UWP to fix canary build

---

doc/material-dsp.md

docs: added UnoDspImportColor mention

---

build/stage-determine-changes.yml

Include .markdownlint.json and cspell.json as part of the documentation changes to avoid ci running the full build in some conditions

ci: Include .markdownlint.json and cspell.json as part of the documentation

---

doc/fluent-getting-started.md

docs: Remove redundant spaces in sample code

---

doc/material-colors.md
src/library/Uno.Themes/Styles/Applications/Common/SharedColorPalette.xaml

- Bugfix
While working on samples I noticed that the Selected opacity from Material and Figma did not match the value in Uno Themes.
Details shared previously by @NVLudwig [here](https://github.com/unoplatform/Uno.Themes/issues/1000#issuecomment-1749431493) included an erratum for Selected opacity. It should be 8% instead of 16%.
@NVLudwig verified Material, his Excel file, and Figma files - they all converged to 8% opacity.

fix: Adjust Selected Opacity

---

src/library/Uno.Material/Styles/Controls/v2/TextBox.xaml

fix: Properly set material TextBox padding

---

doc/material-migration.md

docs: Add TextBox Placeholder and Header breaking change section

---

doc/material-migration.md
src/library/Uno.Material/Styles/Controls/v2/TextBox.xaml
src/samples/UWP/Uno.Themes.Samples.Shared/Content/Controls/TextBoxSamplePage.xaml
src/samples/UWP/Uno.Themes.Samples.Shared/Content/Controls/TextBoxSamplePage.xaml.cs

﻿GitHub Issue: unoplatform/Uno.Themes#1451
- Bugfix
When `TextBox` was disabled PlaceholderText and Header were not properly placed.

fix: ensure attribute animations respond to code changes

---

src/library/Uno.Material/Styles/Controls/v2/TextBox.xaml

﻿GitHub Issue: closes #1443 
- Bugfix
Fixed TextBox Text not aligning with the Icon

fix: Texts not align with the Icon

---

doc/material-migration.md

﻿GitHub Issue: https://github.com/unoplatform/private/issues/504

chore: Update Uno.Material palette link

---

src/library/Uno.Material/Styles/Controls/v2/AppBarButton.xaml
src/library/Uno.Material/Styles/Controls/v2/CommandBar.xaml
src/library/Uno.Themes/Styles/Applications/Common/Converters.xaml

closes https://github.com/unoplatform/uno.chefs/issues/1324
Refactor AppBarButton styles to their own file.
Use lightweight resources AppBarButtonWidth and AppBarButtonHeight

fix: material appbarbutton styles + converter bug

---

src/library/Uno.Material/Styles/Controls/v1/ComboBox.xaml
src/library/Uno.Material/Styles/Controls/v2/Button.xaml
src/library/Uno.Material/Styles/Controls/v2/ComboBox.xaml
src/library/Uno.Material/Styles/Controls/v2/TextBox.xaml

Windows compilation in Debug does not generate the same merged xaml as it does in Release. Causing missing namespace aliases to fail compilation
Odd behaviour with ThemeDictionaries needing to be the first element in a ResourceDictionary

fix: add missing xmlns, themedict ordering

---

src/library/Uno.Material/Styles/Controls/v2/Flyout.xaml

fixes #1506
Do not force the Height property on the MenuFlyoutSeparator style

fix: adjust FlyoutMenuSeparator style

---

doc/material-dsp.md

docs: fix material getting started link

---

src/library/Uno.Material/Styles/Controls/v2/MediaPlayerElement.xaml

﻿GitHub Issue: https://github.com/unoplatform/uno-private/issues/1163
- Bugfix

fix(MediaTransportControls) MPE controls sizing

---

version.json

This is an automated version bump of the  **master** branch after the creation of the release branch release/stable/5.6, based on #1541

Version bump after 5.6 release branch

---

build/templates/nuget-publish-dev.yml

GitHub Issue (If applicable): closes #
Updated condition to allow publishing for both `master` and `release/stable/*` branches for the Uno Internal Dev Feed, while continuing to skip pull request builds. As manual release review check is done before this step for `release/stable/*` branches anyway: 
https://github.com/unoplatform/Uno.Themes/blob/470f874aa1063966def129aee41c213d3327f68e/build/publish/publish-nuget-prod-dev.yml#L4

ci: Adjust condition for the "Publish to Uno Dev Feed" step
